### ISSUE TITLE
Dotmesh usage metrics for backend

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#109]
In order to understand what our SaaS users doing we want to track all their dm usage against our dotmesh cluster.

Things to note:
 * Consider this in our GDPR consent!
 * Monitor the tracking data

We want to know when users have:
* Installed it 
* Pushed/pulled etc

**Comment by alaric-datamesh** [comment]
I'm concerned that as the SaaS takes off, this will become a lot of work to hammer the Segment APIs. I'm assuming they won't rate-limit us, but if I'm to look into batching pings, or putting them into a local queue and having a pool of processes feeding them up to Segment, can I just confirm that it's OK if events are delayed sometimes (hours at worst) in the name of making the system more scaleable and fault-tolerant?

**Comment by prisamuel** [comment]
@mrmrcoleman and @alice-sowerby ^

**Comment by alaric-datamesh** [comment]
The implementation of this is being split into a few different items, so I'm closing this issue:

 - https://github.com/dotmesh-io/marketing-site/issues/49 to get customer IDs from the marketing site into the SaaS UI
 -  https://github.com/dotmesh-io/dothub/issues/32 to get customer IDs from the SaaS UI into the SaaS core
 - #286 to log API calls against that customer ID.
