### ISSUE TITLE
Make git hosting ready and support external contributors smoothly

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#111]
As an open source developer, I'd like to be able to access the Datamesh source code in github so that I can submit tickets, and all the things you'd expect to be able to do when interacting with a modern open-source git project.

Therefore, we should probably:

- [x] Fix gitlab <-> github syncing (e.g. force pushes to github to ensure they always work, and pull back)
- [x] Tidy up existing tickets to be sure they're ready for public viewing
- [x] Make the datamesh repo public on github on the launch date
- [x] Move gitlab to gitlab.datamesh.io
- [ ] We also need a github bot which we can use to permit running of untrusted contributed code on our CI infrastructure after manual inspection. 
- [ ] [GitLab 10.6](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/) now supports the feature we want: showing CI results in GitHub for builds. We should enable it.

**Comment by lukemarsden** [comment]
[GitLab 10.6](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/) now supports the feature we want: showing CI results in GitHub for builds.

In order to make it work for external contributors, we need a bot which we can tell to validate running CI against arbitrary code.
