### ISSUE TITLE
Expose commits via Kubernetes-native UI

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#115]
As a k8s user, I'd like to be able to snapshot my DM volumes using the prototype interface outlined in https://blog.jetstack.io/blog/volume-snapshotting/ so that I don't need to learn some weird `dm commit` command lines.

Therefore, we should take a look at the sample implementation linked to from that blog post and make one of our own.

We can make our existing provisioner able to provision snapshots, rather than needing a second provisioner, IF we first implement the ability to mount snapshots read-only as per #57.

**Comment by lukemarsden** [comment]
https://github.com/dotmesh-io/roadmap/issues/39

**Comment by Godley** [comment]
This is olllllllld. And not our main focus. Closing for now, reopen when ready.
