### ISSUE TITLE
file api

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#121]
see https://docs.google.com/document/d/1MdKWEIG16Z5V2bGipxsr7V5alH_MV2wq1tQ5qDr53dA/edit#

**Comment by lukemarsden** [comment]
@mhausenblas is working on this at https://github.com/dotmesh-io/dotmesh-s3

**Comment by alaric-datamesh** [comment]
Rather than extending the API, considering using the S3 protocol under the hood as we want that anyway (#122); then just provide a way to access that nicely from Python.

Blocked as dependent on #122 if we continue with this approach.

**Comment by lukemarsden** [comment]
closing as dupe of https://github.com/dotmesh-io/dotmesh/issues/122
