### ISSUE TITLE
s3 api

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#122]
**As a** dotmesh user
**I want** to use an S3 API to interact with my dots
**So that**  I can point my existing applications that use S3 to using data stored as dots instead.

similar to https://github.com/datamesh-io/datamesh/issues/121, could expose s3 api / server also
- [ ] add S3 API for a dot as an object accessible via Python SDK for convenience

**Comment by alaric-datamesh** [comment]
Blocked as a third party is working on one for us!

**Comment by lukemarsden** [comment]
we'll need this for the leaderboard soon...

**Comment by Godley** [comment]
Going to take a stab at the backend of this for frontend-ng#111 work

**Comment by Godley** [comment]
`put`ting objects is now implemented - going to close this for now and start to open smaller tickets for the other apis.
