### ISSUE TITLE
Document our API

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#146]
The API is the primary way one dm instance talks to another, and the CLI or client libraries talk to a dm cluster.

More importantly, it provides two key benefits:

1. Exposes unforeseen use of our services to a broader community, enabling people to extend datamesh, thus making it more useful and sticky to others.
2. Forces us to elucidate what our business and technology primitives are, what can and cannot be done with them, and where we think they will go.

Complicating matters, we have several potential tiers of service providers:

1. OSS free tier services, whether locally installed or cloud
2. enterprise restricted commercial services, whether locally installed or cloud
3. cloud-only services

This issue is a request to have a clearly documented network-accessible API (should it be in its own repo?) to encourage a detailed listing of and discussion around these three tiers and what their primitives are.

/cc @lukemarsden

**Comment by lukemarsden** [comment]
done! yay! thanks @alaric-datamesh
