### ISSUE TITLE
Platform support

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#153]
Ensure we support the platforms we say we support: ZFS modules for some major platforms, test that dm works and installs

**Comment by lukemarsden** [comment]
We now think we have support for: CentOS 7, Ubuntu 14.04 on Travis-CI, docker4x (Mac, Windows, AWS etc), Ubuntu 16.04+ (no kernel modules needed).

We could do a better job of continuously testing this support (CentOS 7, Ubuntu 14.04 on Travis-CI), though.
