### ISSUE TITLE
CI SDKs for Python & Go (later Node, Ruby, Java)

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#154]
Design doc: https://docs.google.com/document/d/1MdKWEIG16Z5V2bGipxsr7V5alH_MV2wq1tQ5qDr53dA/edit#heading=h.n9dosapsoikm

Primary goal of this effort is to enable CI caching workflows.

Roadmap item: https://github.com/dotmesh-io/roadmap/issues/6

**Comment by lukemarsden** [comment]
We have a Python SDK! ✨

Thanks to @mhausenblas 😄 

https://github.com/dotmesh-io/python-sdk

**Comment by lukemarsden** [comment]
Closing until we decide to pick up https://github.com/dotmesh-io/roadmap/issues/6
