### ISSUE TITLE
Get macOS docker auto-upgrade working

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#163]
Currently it's disabled (`crontab -e`) because newer versions of docker failed to upgrade automatically with:

```
+ ./scripts/install.sh stable
+ version=stable
+ curl -sSL -o Docker.dmg https://download.docker.com/mac/stable/Docker.dmg
+ hdiutil mount Docker.dmg
hdiutil: mount failed - no mountable file systems
```

Relates to: https://github.com/dotmesh-io/auto-upgrade-docker

**Comment by Godley** [comment]
Don't think we have time to do this, reopen when we do
