### ISSUE TITLE
extend smoke tests to try pushing

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#17]
to catch bugs in macos implementation that would otherwise remain hidden

push to the dothub (and then cleanup) instead!

also make the smoke tests run every hour.

**Comment by lukemarsden** [comment]
also make the smoke tests run every hour.

**Comment by alaric-datamesh** [comment]
Moved running them once an hour out into https://github.com/dotmesh-io/dotmesh/issues/402.

Found the following failures with it:

* https://github.com/dotmesh-io/dotmesh/issues/403
* https://github.com/dotmesh-io/dotmesh/issues/404
