### ISSUE TITLE
[2/4d] Put more state in the state machines

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#186]
In the DM server, we have the state machines defined in statemachines.go managing each filesystem. However, we also have a lot of other things stored in global hashmaps on filesystem ID in the InMemoryState, protected by their own locks. Generally, changes come in from etcd and update those maps directly and/or notify the state machine; but the state machine only does one thing at a time, and some of those things are long-running, so the state machine and the other state can often get out of synch. This complicates code dealing with that state, which has to deal with various different possibilities.

What would be nicer is to say that all data about a filesystem is managed by the state machine. Let there be a global hashmap from filesystem ID to state machine with its own lock, and everything goes through that; read access to the state in the statemachine is then guarded by finer-grained per-filesystem locks, and updating that state is performed by the statemachine itself based on its state transitions (driven by inputs from etcd, ultimately), so the state is always in synch with the SM's view of the world.

This will simplify the code in a way that will make architectural changes for, eg, Cloud Volumes V2 easier. The deletion work was hampered greatly by the state for every filesystem being scattered over lots of different places that got updated on different schedules.

---

Progress and plans:

- [x] abstract InMemoryState inside the fsMachine as an interface so we don't have to pass it in there
- [x] refactor existing usage inside the state machines to use the new state interface
- [x] move types into a `types` package (such as Snapshot)
- [x] move fsMachine to a separate package
- [x] move maps and locks from the InMemoryState into the fsMachine
- [x] refactor existing functions that are using InMemoryState directly to go through the fsMachine
- [x] make tests pass :) 
- [x] remove existing state machine code from the `main` package which is no longer being used

**Comment by lukemarsden** [comment]
This is a big broken window that @alaric-datamesh and I would like to fix before we stop doing "flakes/broken windows week".

**Comment by alaric-datamesh** [comment]
Rather than doing it just as a flakes-week thing, we should probably roll this into the start of the next major work we do on the statemachines.

**Comment by lukemarsden** [comment]
We should make deletion into an explicit state as we do this

**Comment by lukemarsden** [comment]
We should also make sure that pushes and pulls don't interfere with other state machines state but rather delegate appropriately
