### ISSUE TITLE
Tidy up old tickets

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#187]
We have lots of tickets that are duplicates or already done as part of something else, or just don't apply any more. Left over from the wild early days when ideas flowed freely.

Also, lots of tickets are done but I just dragged them to the Done column and didn't close them.

We should go through all 186 tickets before this one and quickly triage them, closing boring ones and properly filing good ones.

**Comment by prisamuel** [comment]
This is an ongoing task. Propose that there should be a better way of culling the backlog, with a pair going through all issues logged during the week every week.
