### ISSUE TITLE
Ensure the frontend stripe test is not flakey

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#188]
We need to make sure that the frontend test for Stripe is not flakey - we had a problem where the iframe was not appearing causing the test to fail - we are unsure why - the same test is passing consistently on another stack (farmbooking -@binocarlos 's stack).

To close this issue - apply whatever is making the farmbooking stripe test pass consistently to our test - most likely the timeout waiting for the stripe ui to appear is the cause

**Comment by alaric-datamesh** [comment]
This looks like part of epic #296
