### ISSUE TITLE
A cluster with many users slows down the collaborator list

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#189]
I’ve had the same local cluster running all day with many test runs therefore adding many users.  Then the endtoend.js test started being flaky (which was good because I added some anti-flake measures)...

Watching the video, the collaborators page never loaded - I'm wagering it's because there was so much data being loaded it triggered the test timeout...

Soon as I reset the cluster - everything started passing consistently so this shouldn't be a problem for CI...

To close this issue - optimise the collaborators page to not load so much data - write a test that adds a thousand users to make sure this works.

**Comment by alaric-datamesh** [comment]
This is part of epic https://github.com/dotmesh-io/dotmesh/issues/321

**Comment by danthebaker** [comment]
Not relevant anymore.
