### ISSUE TITLE
a user-facing dm diagnostics command

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#191]
to collect information that would be useful for bug reports?

**Comment by lukemarsden** [comment]
We have the startings of this at https://github.com/dotmesh-io/ops/tree/master/diagnostics + `dm debug DotmeshRPC.DumpInternalState`, but still need to turn it into a user-facing command and figure out how to access all the nodes individually (or have them fan out).

**Comment by Godley** [comment]
Nice to have, but think dm debug is enough for now. Reopen when we have time
