### ISSUE TITLE
dm cluster init is not idempotent

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#192]
If I run `dm cluster init` on a clean docker install, it installs and returns `0`. 
If I run `dm cluster init` on a docker setup that already has a cluster running, it returns `1`. 

Ideally, I should be able to run `dm cluster init` and always end up with a valid cluster, always returning `0`, returning non-zero only if I failed to get to a good cluster state (e.g. could not download images).

This makes automated scripting fail.

```
$ dm cluster init
Checking suitable Docker is installed... assuming post-semver Docker client is sufficient.
assuming post-semver Docker server is sufficient.
Checking dotmesh isn't running... dotmesh-etcd container already exists!

$ echo $?
1
```

**Comment by lukemarsden** [comment]
fixed now! thanks @alaric-datamesh !
