### ISSUE TITLE
Make dm client available as a docker container

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#193]
Right now, the only way to get the `dm` client is `curl .... && chmod +x /usr/local/bin/dm`. 

This can be a challenge in environments where you cannot install things, and can be a messy "two-step", especially cross-platform (Windows, etc.) and in controlled environments (notably CI/CD).

We need a simple container image with just the `dm` binary, whose `ENTRYPOINT` is `dm`, so I can do:

```
$ docker run --rm dotmesh/dm cluster init
```

etc.

Of course, I likely will need to bind-mount in things, like `/var/run/docker.sock`, but it is more than acceptable.

**Comment by Godley** [comment]
No time for this, reopen when it's needed
