### ISSUE TITLE
add custom segment events for saas

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#202]
We want to send custom events to segment for each of the obvious user interactions like payment succeeded / dot created - this is from both the perspective of the saas frontend and the servers on the backend

**Comment by alaric-datamesh** [comment]
Part of epic https://github.com/dotmesh-io/non-coding-tasks/issues/34

**Comment by alice-sowerby** [comment]
This will be implemented/is part of the SaaS front end rework. Also, partly fulfilled by https://github.com/dotmesh-io/dotmesh/issues/114 
https://github.com/dotmesh-io/dothub/issues/1

**Comment by alaric-dotmesh** [comment]
Made redundant by https://github.com/dotmesh-io/frontend-ng/issues/70
