### ISSUE TITLE
plug more destinations into segment (?)

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#203]
We need to activate the range of segment backends and more importantly configure the reports we need and iterate with the engineers to add the incoming input events that drive those reports

**Comment by alaric-datamesh** [comment]
Part of epic https://github.com/dotmesh-io/non-coding-tasks/issues/34

**Comment by lukemarsden** [comment]
Depends on requirements from metrics banner.

**Comment by lukemarsden** [comment]
cc @alice-sowerby

**Comment by alice-sowerby** [comment]
No specific work item, we need to close this and raise more specific issues when we know what we want.
