### ISSUE TITLE
work out how to split the segment events between various sources

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#204]
Do we have multiple segment projects or a single project and use event filters to decide which site the event was from?

The downside of multiple projects is having to configure everything.

To close this issue we need to make a decision between multiple projects or single project and make this work by capturing events from:

 * saas
 * marketing
 * docs
 * backend
 * versioner

Each service either submits to a different segment project or includes a `project` field in the event

**Comment by alaric-datamesh** [comment]
Part of epic https://github.com/dotmesh-io/non-coding-tasks/issues/34

**Comment by danthebaker** [comment]
Decision made before launch to have multiple projects.
