### ISSUE TITLE
Going to a dothub.com page without logging in shows a page with missing data

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#217]
It should redirect to a login page.

To test:

1. Open a browser window in which you are not logged in (I just used an incognito window)
2. Go to a page that normally requires login (I did the API Key page https://dothub.com/ui/settings/apikey )
3. See a strange page (See attached).

<img width="1149" alt="screen shot 2018-02-01 at 12 54 23 pm" src="https://user-images.githubusercontent.com/282526/35674973-14a3fba2-074f-11e8-8846-9ef4dbf8ca34.png">

**Comment by alaric-dotmesh** [comment]
This needs moving to the dothub repo!

**Comment by alaric-dotmesh** [comment]
This should be fixed automatically as part of the frontend-ng work!
