### ISSUE TITLE
Make a convenient install script

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#220]
Just like you can do `curl https://get.docker.com | sh -`, and the script figures out your platform and installs, should have `curl https://get.dotmesh.io | sh - ` and it will work on any platform.

**Comment by alaric-dotmesh** [comment]
Won't fix - it's not better enough than curl for the `dm` binary then running `dm cluster init`, and piping from URLs into bash as root is evil :-)

**Comment by deitch** [comment]
> piping from URLs into bash as root is evil

Well, I don't think it is as bad as `eval()`, but...

We still need an easier way to install. Homebrew? Not sure.
