### ISSUE TITLE
can we make dotmesh-server massively smaller?

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#221]
The actual binaries are 89M:

```
$ docker run -it --rm --entrypoint=sh quay.io/dotmesh/dotmesh-server
# cd /usr/local/bin
# du -s -h /usr/local/bin
89M	/usr/local/bin
```

But the image itself is 3X:

```
$ docker image ls | grep dotm
quay.io/dotmesh/dotmesh-server                           latest                                                 869dd1069db1        20 hours ago        282MB
```

Can we get this down by going alpine Linux or even `FROM scratch`?

**Comment by Godley** [comment]
The problem here presumably would be userland modules for zfs, but in line with https://github.com/dotmesh-io/ops/issues/97 we should look into this at some point. Reopen when that issue rises to the top of the prio list :)
