### ISSUE TITLE
can’t clone a dot that was cloned before after deleting it locally

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#242]
it just hangs

alaric [12:41 PM]
Uhoh

luke [12:41 PM]
i can workaround it :slightly_smiling_face:

alaric [12:41 PM]
So, you clone it, delete it, then try to clone it again?

luke [12:41 PM]
yes
actually, i cloned a _branch_ first
then deleted the whole dot
then tried to clone master

alaric [12:41 PM]
Be interested to know if the problem persists when cloning it *to a new name* - I suspect it will persist due to the problem being at the fsid layer
Quite possibly the new clone collides with the old state that's still being cleared up

luke [12:42 PM]
the filesystem in the hub has the same ids throughout of course

**Comment by lukemarsden** [comment]
this could be because the old state still exists, or it could be because the fsid is now in the tombstone list. need a way to undelete things that someone decides they _do_ want to have pull down after all.

**Comment by alaric-datamesh** [comment]
Believed to be fixed.
