### ISSUE TITLE
public, read-only dots would be useful for our own tutorial purposes

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#247]
it would be great for the Collaboration tutorial not to require someone to have gone through the Library tutorial, but rather, to be able to pull down public read-only dots with the example data in them.

@deitch mentioned that this would have been helpful in his CI examples too.

**Comment by deitch** [comment]
Very much so. I thought I’d opened an issue, but apparently not. 

They don’t need to be read only in any special way. It’s enough that they belong to an account that other users can read.

**Comment by alaric-datamesh** [comment]
Read-only dots are on the roadmap: https://github.com/dotmesh-io/roadmap/issues/36

Public dots are on the roadmap: https://github.com/dotmesh-io/roadmap/issues/42
