### ISSUE TITLE
Change dependency management from godeps to deps.

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#252]
After much debate in the community, golang has decided to officially supports 'deps' in favour of 'godeps'.

https://golang.github.io/dep/

It is better documented and also contains migration steps from godeps to deps.

We need to do this for each thing we build:

 - dm
    - [x] cmd/dm
    - [x] cmd/dotmesh-server/pkg/main
    - [x] cmd/dotmesh-server/pkg/dynamic-provisioner
    - [x] cmd/dotmesh-server/pkg/flexvolume
 - [X] checkpoint-service

**Comment by alaric-datamesh** [comment]
Done. Now use `dep ensure` instead of all that `godep save ./...` stuff.
