### ISSUE TITLE
If there is only one dot, automatically switch to it. 

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/dotmesh#253]
During UX testing we saw that users were not familiar with the idea of switching to a dot when following the steps: 

> Start the app.
> 
> `docker-compose up -d`
> 
> You can see that the datadot referenced in the docker-compose file has been created.
> 
> `dm list`
> 
> Make moby_counter the current datadot.
> 
> `dm switch moby_counter`
> 
> This means that later dm commands will operate on that datadot, as indicated by a *.

The suggested change is to pre-select the only existing dot when the number of dots == 1

**Comment by alaric-datamesh** [comment]
Done. I also improved the error messages around this area a bit.
