### ISSUE TITLE
Do not display red text in terminal when nothing is wrong

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/dotmesh#255]
In user testing we saw that users were perturbed when they saw red text in the terminal when doing `docker-compose up -d` locally. 

It’s when it does something with node.js
Probably just need to add a `2>/dev/null` to a Dockerfile as a quick workaround?

(Luke's comments)

**Comment by binocarlos** [comment]
This is because of non-important warnings when doing `npm install` - the fix `2>/dev/null` will work

**Comment by lukemarsden** [comment]
@binocarlos fixed this in https://github.com/dotmesh-io/moby-counter/commit/efed9594065ae705c1ec4b8cfffb8bfabcbd4bf5
