### ISSUE TITLE
release dotmesh 0.1

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#256]
actually release dotmesh 0.1!

## url structure

we currently have:
* [_stable url_] `get.dotmesh.io/{Linux,Darwin}/dm` -> latest stable? (binary just gets put there, later turn into redirect?)

we want, in addition:
* [_master builds url_] `get.dotmesh.io/unstable/master/{Linux,Darwin}/dm`

## the plan! before the release:
- [x] clear up test release on github page [priya]

## dm binaries and yaml
- [x] make master builds and yaml NOT deploy to _stable url_, make them deploy to `get.dotmesh.io/unstable/<branch>` instead [alaric]
- [x] make release builds and yaml deploy to _stable url_. [alaric]
- [x] build step that builds yaml and sticks in version, e.g. `:<version>` tags on all our quay.io images [alaric]
- [x] dm cluster {join,init,upgrade} - upgrades you to the baked-in version (`dm` client knows its own version, and version of its corresponding docker images for server etc) [alaric]
- [x] upgrading section in the docs at https://docs.dotmesh.com/install-setup/upgrading/ [alaric] 
- [x] check link to the upgrade instructions in the docs from the `dm version` command output is valid

## do the release
- [x] `git checkout -b release-0.1` from master, push to gitlab [everyone, together]
- [ ] delete `:latest` tag on ALL our quay.io images [alaric + luke]
- [x] redeploy checkpoint to reset its 4 hour cache.
## later:
- [ ] implement semver logic to avoid release 0.1.1 after 0.2.0 clobbering "latest stable"
- [x] document the release process
## questions

how to get version in CI? something like `(cd versioner && go run)`

**Comment by alaric-datamesh** [comment]
NOTE: Our previous work on this means that we push all Docker images to quay.io with the full git hash as the "tag", not our nice versioner output strings - which is fine, as they're not really user-visible, and it
makes some things a lot simpler.

**Comment by alaric-datamesh** [comment]
I've made the "make release builds and yaml deply to stable url" step a manual job we can press in gitlab, pending semver logic to press it automatically.

**Comment by prisamuel** [comment]
Moved remaining items out of this into separate issues.
