### ISSUE TITLE
Support external disks for dotmesh storage

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#259]
Right now, it appears that dotmesh server's local deploy sets up a fairly small (10GB?) zpool on local disk in `/var`. That is great as a starting point, but only goes so far.

We need a way to support external storage as a zpool, so that users can have the same great experience of "just deploy" without having to know or understand zfs, but get unlimited storage of their own.

Some possible directions:

* direct attached block storage
* files on direct attached storage
* files on local filesystem
* files on NFS
* EBS or other cloud block storage

EBS or other cloud block storage is particularly appealing in Kubernetes, where there are drivers to automate PV provisioning from such storage.

The key is to give users options to:

1. Select a different storage for the underlying zpool
2. Select a specific size to use

**Comment by deitch** [comment]
cc @lukemarsden @alaric-datamesh

**Comment by deitch** [comment]
Note: this will be important in enterprises, where some have diskless blade servers attached to a SAN, but others have specific data-file allocation structures and policies.

**Comment by lukemarsden** [comment]
"CVv2" includes support for provisioning disks via Kubernetes for dotmesh to use.

**Comment by deitch** [comment]
> support for provisioning disks via Kubernetes for dotmesh to use

Been a while since I looked at cvv2, refreshing now. How would this work?

**Comment by lukemarsden** [comment]
I'll explain verbally next time we talk. :)

**Comment by vvangestel** [comment]
We would like to use dotmesh with rook-blocks as PV's to snapshot our databases. Will CVv2 make this possible?

**Comment by lukemarsden** [comment]
Yes, it will!

**Comment by alaric-datamesh** [comment]
I'm working on it as we speak, and... it'll be done as soon as it's done ;-) Watch this space and thanks for the offer!

**Comment by alaric-datamesh** [comment]
This is being fixed on Kubernetes by #100, and can be done on non-Kube clusters by using `--use-pool-dir` for `dm cluster init`.
