### ISSUE TITLE
Add IP of nodes into checkpoint service to be sent out to segment

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#262]
The metrics that we have now are the following (userId being the unique ID for the node which runs the dotmesh-server)

```  
UserId: "a0b1933a49c3dd0b",
  Event: "VersionUpdateCheck",
  Properties: map[string]interface{}{
    "Arch": "Linux 95317b08a2e4 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux",
    "ForwardProxyIP": "10.154.0.3",
    "InstalledVersion": "master-a5270d8",
    "NumberOfDots": "0",
    "OS": "Ubuntu 17.10 \n \l",
    "Product": "dotmesh-server",
    "RemoteIP": "10.36.1.6",
    "ServersInCluster": "",
    "TotalCurrentDotSizeBytes": "0",

```
There are several metrics that we can track in addition to this. One metric that was suggested early on was the originating IP address. That seems to be quite tricky as checkpoint is behind kubelego(nginx ingress) and cloudflare, and we seem to only get an internal IP in the metrics.

Metrics to add:
- [ ] The highest priority appears to be the orignating IP address i.e the external IP address of the machine running dotmesh-server
- [ ] Number of remotes
- [ ] Whether dothub is a remote, and if present, the dothub username/id

**Comment by lukemarsden** [comment]
we don't need "Whether dothub is a remote, and if present, the dothub username/id", because https://github.com/dotmesh-io/dotmesh/issues/286 gives us the same information.

Let's just get the originating IP address, and call this done :)

**Comment by prisamuel** [comment]
After some digging:

The nginx ingress controller sees
```
10.154.0.7 - [10.154.0.7] - - [28/Mar/2018:15:09:11 +0000] "GET /v1/check/dotmesh-server?arch=Linux+d1eeeb011f21+4.4.0-109-generic+%23132-Ubuntu+SMP+Tue+Jan+9+19%3A52%3A39+UTC+2018+x86_64+x86_64+x86_64+GNU%2FLinux&flag_NumberOfDots=0&flag_ServerID=c192d2be2a65cb29&flag_ServersInCluster=&flag_TotalCurrentDotSizeBytes=0&os=Ubuntu+17.10+%5Cn+%5Cl&signature=&version=release-0.3.3 HTTP/2.0" 200 322 "-" "HashiCorp/go-checkpoint" 302 0.003 10.60.1.45:8080 285 0.003 200
```
Where the incoming IP (10.154.0.7) is the kubernetes node IP. 

The checkpoint request flow is from dotmesh-server -> cloudflare (only DNS) -> Ingress nginx  (HTTPS) with kube-lego  (HTTPS) -> checkpoint service container.

client-IP is already being replaced by kubernetes when the request reaches the ingress nginx logs.

**Comment by prisamuel** [comment]
https://stackoverflow.com/questions/36464890/how-to-access-client-ip-of-an-http-request-from-google-container-engine

**Comment by prisamuel** [comment]
https://support.cloudflare.com/hc/en-us/articles/115000219871

I read the manual (cloudflare) and I've updated the cloudflare settings to now do two things
- Redirect all requests with scheme “http” to “https”. This applies to all http requests to the zone.
- Full SSL (strict): Your origin has a valid certificate (not expired and signed by a trusted CA or Cloudflare Origin CA) installed. Cloudflare will connect over HTTPS and verify the cert on each request.

We now get the client-IP and the country code into segment. Cloudflare sets the X-forwarded-for, X-real-ip and cf-connectig-ip to be the client external IP address. It also set a cf-country which is the two letter country code determined from the connecting ip. This info is now in segment.

```
client.Track(&analytics.Track{
  UserId: "3fb75f4cd58a41f1",
  Event: "VersionUpdateCheck",
  Properties: map[string]interface{}{
    "Arch": "Linux b621b575ba49 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux",
    "CFCountry": "DE",
    "InstalledVersion": "release-0.4.0",
    "NumberOfDots": "0",
    "OS": "Ubuntu 17.10 \n \l",
    "OtherServersInCluster": "",
    "Product": "dotmesh-server",
    "RequestHeaders": "Cf-Visitor:[{\"scheme\":\"https\"}] Accept:[application/json] Connection:[close] X-Forwarded-For:[148.251.0.20, 148.251.0.20] X-Forwarded-Host:[checkpoint.dotmesh.com] Accept-Encoding:[gzip] User-Agent:[HashiCorp/go-checkpoint] X-Real-Ip:[148.251.0.20] X-Forwarded-Proto:[https] Cf-Ipcountry:[DE] Cf-Connecting-Ip:[148.251.0.20] X-Forwarded-Port:[443] Cf-Ray:[408c59ddd8fe231e-FRA] ",
    "TotalCurrentDotSizeBytes": "0",
    "X-Forwarded-For": "148.251.0.20, 148.251.0.20",
  },
})
```

Currently creating basic reports on google studio.
