### ISSUE TITLE
GKE /var/lib/dotmesh not allowing zpool to create pool

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#264]
When running a k8s v1.8.7-gke.1 cluster on GKE with:

 * kernel: 4.4.0-1027-gke 
 * os: Ubuntu 16.04

The Kubernetes YAML had:

```yaml
- name: USE_POOL_DIR
  value: /var/lib/docker/dotmesh
```

And I got this error:

```
+ echo 'ZFS already loaded :)'
+ '[' '!' -e /dev/zfs ']'
+ zpool status pool
cannot open 'pool': no such pool
+ '[' '!' -f /var/lib/dotmesh/dotmesh_data ']'
+ truncate -s 10G /var/lib/dotmesh/dotmesh_data
+ echo zpool create -m /var/lib/dotmesh/mnt pool /var/lib/dotmesh/dotmesh_data
+ zpool create -m /var/lib/dotmesh/mnt pool /var/lib/dotmesh/dotmesh_data
ZFS already loaded :)
zpool create -m /var/lib/dotmesh/mnt pool /var/lib/dotmesh/dotmesh_data
cannot create 'pool': no such pool or dataset
```

Changing `USE_POOL_DIR` to ` /var/lib/docker/dotmesh` got it working - to close this issue investigate why require_zfs.sh fails to use `/var/lib/dotmesh` on GKE

**Comment by lukemarsden** [comment]
fixed by http://gitlab.dotmesh.io:9999/dotmesh/dotmesh/commit/35a5ea5019e593e8e7de1335c3f69eef901d7f7a
