### ISSUE TITLE
flexvolume driver should read creds from the secret, not /root/.dotmesh

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#265]
https://docs.dotmesh.com/install-setup/gke/#dotmesh-config

<img width="723" alt="screen shot 2018-02-07 at 06 34 13" src="https://user-images.githubusercontent.com/264658/35901893-f1c425ae-0bd0-11e8-9dbb-4af7f1a8cfd0.png">

This wrinkle is caused by the fact that the flexvolume driver doesn't read creds to talk to dotmesh from the kubernetes secret.

**Comment by lukemarsden** [comment]
http://gitlab.dotmesh.io:9999/dotmesh/dotmesh/blob/7e22e1fa39ecc45f5b0d263b5fa39c0529cf8876/cmd/dotmesh-server/pkg/flexvolume/flexvolume.go#L72

**Comment by lukemarsden** [comment]
Gone from the docs!

**Comment by alaric-datamesh** [comment]
Made redundant due to having a unix-domain socket for flexvolume to talk to the DM server!
