### ISSUE TITLE
--dot and --branch flags to all dm commands that use a "current" thing

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#266]
The interactive model for single-user dm usage is to have a "current" dot and branch marked with a `*` in the output of `dm list` and `dm branch` respectively.

This falls down in multi-user, concurrent situations, so we need a way to spell out which one we mean.

Simply adding optional `--dot` and `--branch` flags to override the "current" for all commands where might otherwise be used should be sufficient.

**Comment by deitch** [comment]
As requested by @lukemarsden , related issues: #197 #198

**Comment by Godley** [comment]
Don't have time to do this right now, reopen when needed
