### ISSUE TITLE
figure out how to access dotmesh server on kubernetes on docker for mac

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#268]
experimentation suggests that `hostPort` is not supported, so we need a different mechanism here. given that it's a single node only, `nodePort` should work fine.

provide alternative dotmesh yaml for Docker for Mac which exposes the dotmesh service in a way that means it actually gets exposed on localhost.

**Comment by alaric-datamesh** [comment]
This is believed to be fixed now!!! :-D

**Comment by danthebaker** [comment]
`server-docker-for-desktop` pod is created and runs for a few seconds before disappearing. This then loops.
