### ISSUE TITLE
delete :latest tag on ALL our quay.io and local registry images

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#270]
We no longer use the tag :latest, instead use the tag with the hash.

This was moved out of https://github.com/dotmesh-io/dotmesh/issues/256

**Comment by prisamuel** [comment]
For testing, we use the `latest` tag on all images that are built and pushed to quay on CI. On local builds we use the tag `latest` on all images that are built and pushed to the local registry. 

In order to use a versioned image for testing the ci-tools/testtools.go would need to be configured to pull specific versions instead of `latest`. 

Approach:
- Pass the CI_DOCKER_TAG env var from the build script, and use that variable name in testtools.go.
- Need to check the behaviour of the end-to-end tests, AFAIK they pull in a specific version of the system under test and `test-latest` for every other dependency.

**Comment by lukemarsden** [comment]
Still used in citools. Also, still used in local.

Could rename this to `untested-latest` to avoid naïve users `docker pull` getting it.

**Comment by lukemarsden** [comment]
Done enough!
