### ISSUE TITLE
Re-deploying dotmesh-server leads to CrashLoopBackoff

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#276]
Whenever we re-deploy `dotmesh-server` to our GKE cluster - it CrashLoopBackoffs with this error message:

```
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:89: jailing process inside rootfs caused \\\"pivot_root invalid argument\\\"\""
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:89: jailing process inside rootfs caused \\\\\\\"pivot_root invalid argument\\\\\\\"\\\"\"\n"
```

[this issue](https://github.com/moby/moby/issues/23767) describes this in full...

The real workround is to fix #263 because 1.8 does shared mounts properly.

The quick-fix to close this ticket is to put a step into `gitlab.yaml` that logs into the node and does `sudo systemctl restart docker` after a deploy - use `kubectl get no --selector dmserver=true` to get what node it's running on

**Comment by lukemarsden** [comment]
relates: https://github.com/dotmesh-io/dotmesh/issues/322

**Comment by lukemarsden** [comment]
relates: https://github.com/dotmesh-io/dotmesh/issues/275

**Comment by binocarlos** [comment]
The solution is to upgrade the cluster to k8s 1.9 and ensure that bumps docker to version >= 17.03 where the pivot root error no longer happens.  We ran a test of a constant re-deploy for 20 minutes and am confident this will fix this problem.

**Comment by binocarlos** [comment]
This is fixed now that we (finally) got the cluster upgraded to 1.9
