### ISSUE TITLE
Extract all front-end SaaS folders out of dotmesh repo.

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#277]
several stages:

- [x] library for acceptance testing all the parts based on a commit to any part
- [x] split repo into core (open source) and frontend, billin, communication - at this point we can hook github up to gitlab properly and make github the source of truth
- [x] start doing weave cloud + flux

**Comment by binocarlos** [comment]
This is done now - I've documented everything in the [ops repo](https://github.com/dotmesh-io/ops#weave-cloud)
