### ISSUE TITLE
Test flake: macos_docker_edge has erratic x509 issues

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#283]
http://gitlab.dotmesh.io:9999/dotmesh/dotmesh-sync/-/jobs/18295 shows:

```
assuming post-semver Docker server is sufficient.
Checking dotmesh isn't running... done.
Registering new cluster... Get https://discovery.dotmesh.io/new?size=1: x509: certificate signed by unknown authority
ERROR: Job failed: exit status 1
```

It usually goes away when retried. Seems to be a test infrastructure problem rather than a bug.

**Comment by lukemarsden** [comment]
https://github.com/golang/go/issues/16589#issuecomment-278430636 might be related

**Comment by lukemarsden** [comment]
but why it works sometimes on retry I have no idea!

**Comment by lukemarsden** [comment]
I could just upgrade macOS on that runner... but I kinda like having a variety of versions...

**Comment by prisamuel** [comment]
Haven't seen this issue in a while. Closing.
