### ISSUE TITLE
Re-releasing produces mangled versions

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#295]
We need a proper process to re-deploy a release, if the original deploy went wrong (as 0.2.0 did; the tests failed when doing the release build and we had to reset the branch). Partly, we just need to document the correct process, but there's a technical change required as well.

When the 0.2.0 release was [made in Github](https://github.com/dotmesh-io/dotmesh/releases/tag/release-0.2.0), Github created a `release-0.2.0` tag pointing to the same commit as the `release-0.2` branch. For some reason, when gitlab re-ran the build jobs in the existing pipeline triggered by the creation of the `release-0.2` branch, it got excited about this tag pointing to the same commit and checked out the tag rather than the branch - meaning that `CI_COMMIT_REF_NAME` seems to have been `release-0.2.0` rather than `release-0.2`. This upset the versioner.

Suggested solution: Make the versioner, when looking at a git ref name, notice if it's already got a third numeric component. If so, just use it rather than counting commits to create an extra numeric component. Then builds from `release-A.B.C` tags will just automatically get the tag name as a version, which is right and proper.

 - [x] Document how to re-release
 - [x] Make the versioner not be confused by tags

**Comment by prisamuel** [comment]
> Then builds from release-A.B.C tags will just automatically get the tag name as a version, which is right and proper.

Done! 

So now doing a re-release is the same process as doing a release. Can you think of any docs that need updating?
