### ISSUE TITLE
without hostPort, no one will be able to access the cluster from the outside

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#297]
https://github.com/dotmesh-io/dotmesh/issues/292 attempted to make clusters work without functioning hostPort CNI configuration (e.g. default weave net install on a kubeadm cluster).

sadly, I don't think that anyone will be access a non-hostPort cluster from the outside without turning our hostPort service (dotmesh service) into a nodePort service.

should be a simple tweak, but needs testing. we should also rip the hostPort stuff out of our own acceptance tests, to make sure we test this case.

**Comment by lukemarsden** [comment]
nodePort can't run on 6969, need to move to 36969 or do something else (ingress on 6969?)

**Comment by binocarlos** [comment]
I'm having a look around to see if custom ports for ingress are allowed - [here](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/custom-template.md) is one interesting link that talks about custom nginx templates

Perhaps allowing the port to be configured to port 80/433 for the `dm` client would be another approach?

**Comment by lukemarsden** [comment]
We will 
- [ ] change to nodePort on 36969
- [ ] add 36969 as a port that the DM client tries

Later:
- [ ] also try TLS on 443 for non dothub clusters
- [ ] document ingress configuration

**Comment by lukemarsden** [comment]
Although it would be nice to replace 6969 with 36969 rather than supporting both (which needs to be done from the client and the server) upgrades won't work without doing so...

**Comment by lukemarsden** [comment]
Fixed!
