### ISSUE TITLE
speed up our builds by using go1.10 build caching

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#298]
https://golang.org/doc/go1.10#build
https://groups.google.com/forum/#!msg/golang-dev/qfa3mHN4ZPA/X2UzjNV1BAAJ

**Comment by lukemarsden** [comment]
Related: https://github.com/dotmesh-io/dotmesh/issues/181

**Comment by alaric-datamesh** [comment]
Part of epic https://github.com/dotmesh-io/dotmesh/issues/296

**Comment by lukemarsden** [comment]
closing as this is part of https://github.com/dotmesh-io/dotmesh/issues/182 now
