### ISSUE TITLE
dm cluster init doesn't check if dm is fully configured

### ISSUE THREAD

**Issue by brendan-donegan** [dotmesh-io/dotmesh#303]
I ran into an issue where I was trying to run docker-compose with the dm driver and got:

`ERROR: Volume ids.redis specifies nonexistent driver dm`

Running dm cluster init gave me: `Generating PKI assets... PKI directory already exists at /Users/doneganb/.dotmesh/pki, refusing to proceed`

After some debugging it turns out I didn't have the dotmesh-server and dotmesh-server-inner containers running. Presumably I had run dm init successfully at some point and then Docker somehow got reset.

**Comment by lukemarsden** [comment]
We should make `dm cluster init` not fail if PKI is already configured (left over on user's filesystem) but  docker containers aren't running.

**Comment by lukemarsden** [comment]
We should also make other error cases tell you how to recover (`sudo dm cluster reset`).

**Comment by alaric-datamesh** [comment]
This should be much more resilient in the next release!
