### ISSUE TITLE
[EXTRA] Strip newlines from admin password and admin api-key

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#304]
The dotmesh server expects to see the admin api key and admin password in base64 encoded form...

Sometimes - folks (like me) who don't know about `echo -n` submit their credentials with a newline appended to the password or key.

We should pro-actively strip the password and api key of any newlines before using them in `controller.go -> insertInitialAdminPassword`

**Comment by alaric-dotmesh** [comment]
Quick fix, done in the referenced commit above ^^^
