### ISSUE TITLE
Automate running ./prime.sh on ci runners

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#311]
The manual way to do this at the moment involves either checking out the latest code on the runners, and doing a `./prime.sh` OR cd into the latest build directory obtained from CI and doing a `GOPATH=path ./prime.sh` in that dir. 

Make sure the dependency on `dotmesh-instrumentation` is up to date.

**Comment by alaric-datamesh** [comment]
Adding a comment to `prime.sh` might be a useful workaround for now.

Dimly related to epic https://github.com/dotmesh-io/dotmesh/issues/296

**Comment by prisamuel** [comment]
Done!!!!
