### ISSUE TITLE
update vagrant and dev docs to refer to no longer needing anything but registry in dotmesh-instrumentation

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#323]
https://github.com/dotmesh-io/dotmesh/issues/281

**Comment by binocarlos** [comment]
question @lukemarsden do we still needs the discovery service running on vagrant? not sure if the multi-node clusters might still use this?

**Comment by binocarlos** [comment]
Ok - ignore this question - I have read the question and it clearly says only `dotmesh-instrumentation` - sorry for noise :-)

**Comment by binocarlos** [comment]
I've just stood up a fresh vagrant using this setup and it all seems to work fine - closing.
