### ISSUE TITLE
don't print the api key in error messages

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#325]
e.g. when a `dm push` fails, we shouldn't print the api key in the clear

**Comment by prisamuel** [comment]
@lukemarsden and @danthebaker 
Is this still an open issue? If so, can you add an example.

On a push failure (contrived with invalid API keys) I get
```
priya@Priyas-MBP:~$ dm push priyahub priya
Pushing admin/priya to priyahub:priya_test/priya
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"Unable to connect to any of the addresses attempted: [dothub.com], errs: [Permission denied. Please check that your API key is still valid.]","data":null},"id":8674665223082153551}
' yields error Unable to connect to any of the addresses attempted: [dothub.com], errs: [Permission denied. Please check that your API key is still valid.]
```

**Comment by alaric-datamesh** [comment]
Try it with a valid API key, but a push that fails for some other reason? Eg, try to push to `alaric/foo` on the dothub, where you're not user `alaric`, or push to a dot that's got dirty data on the remote?

**Comment by lukemarsden** [comment]
Needs an attempted push/pull/clone in order to trigger the issue (e.g. failed push).

Deserializing the TransferRequest is the culprit.

API key is printed both in logs and stdout. Stdout is slightly more important to fix.

**Comment by prisamuel** [comment]
Done by overriding the toString's of various structs where APIKey is being used, and masking the value for field 'ApiKey" with "****". This has no effect on the JSON serialiser / marshaller.

Some amount of code duplication between the structs the APIKey is defined in both the client and server makes me a bit sad.
