### ISSUE TITLE
Validation of new dot-names should happen in the api 

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#326]
Presently - the CLI and frontend are responsible for validating new names for dots.

The CLI has code to validate new dot names, the frontend does not - this lead to a dot with the name `''><img src=x onerror=prompt(3)>` appearing.

Rather than duplicate the validation logic from the CLI into the frontend - the api should perform the validation and return an appropriate error message that will be displayed.

The CLI and frontend should be aware of such errors and display them accordingly.

**Comment by alaric-dotmesh** [comment]
It's always been the API that did the validation, but it wasn't as thorough as it could be... I've beefed it up now.
