### ISSUE TITLE
We should have a kernel module for the non-Ubuntu GKE kernels

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#328]
we should have a kernel module for the non-Ubuntu GKE kernels (COS)

**Comment by lukemarsden** [comment]
Moving into sprint as this is affecting one users who tried dotmesh on GKE 1.9.

**Comment by lukemarsden** [comment]
We also need to stop dotmesh trying to write `/dotmesh-test-pools` and generally test end-to-end (manually, at least) on GKE with COS.

**Comment by Godley** [comment]
Think a lot has changed since this was opened. Reopen or open new tickets for the relevant kernels (likely to need centos or something soon)
