### ISSUE TITLE
Stop supporting `dm cluster join`

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#332]
Kubernetes is the supported way to make clusters.

- [ ] Remove `dm cluster join`
- [ ] Remove discovery service
- [ ] Simplify `dm cluster init` by removing discovery service stuff and printing of `dm cluster join` command

**Comment by prisamuel** [comment]
Wait for more feedback from users before we can embark on this.

**Comment by lukemarsden** [comment]
The motivation for deleting this is to remove complexity around forked discovery service with dubious security design.
