### ISSUE TITLE
Investigate failover using NFS and service vips on Kubernetes

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#335]
When a storage-node that has a network disk attached fails - Kubernetes will re-schedule the storage-node pod to another node that has labels/affinity and attach the network storage driver to the new storage node - great!

CVv2 will implement the NFS mounts such that service vips are used to access the NFS server.

Question: in the case of failover - will the dotmesh-node (a.k.a. clients) that have existing NFS mount-points that are communicating over k8s service vips automatically failover reliably.

For example - a large amount of data is being written and the NFS server is failing over mid-write.  What happens to the NFS mount-point?

Other more basic example - will the NFS mount-point that is communicating over a service VIP even still work once the service is pointing to a new dotmesh storage-node?

Question: does the magic of k8s service vips migrating migrating happen in a way that will work with NFS?

To close this issue - run some kind of experiment where one node is consuming an NFS mount-point that is using a k8s service vip to point at the NFS server.  Then - failover the NFS server to another node and see what happens with regard to the questions above.

**Comment by alaric-datamesh** [comment]
It seems so. The test for issue #334 failed - we got "stale file handles" - but the NFS mount was still there and managing to get stale file handle errors back from the server! Unmounting and remounting worked fine and reconnected us to the NFS server via a service VIP after it had moved to another k8s node.

So other than the #334 stale file handle issue, this seems to work and we can close this issue. Yay!
