### ISSUE TITLE
Red ticks show up when doing dm cluster init and it looks like a failure

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#338]
<img width="837" alt="red-ticks-problem" src="https://user-images.githubusercontent.com/1676629/37710788-a1b0482a-2d06-11e8-9f55-da7cf3a20b47.png">

We have these lovely utf-8 characters is `dm cluster init` output - they are great!

However - we should not display the red-ticks as shown in the image above - it triggers an immediate `it failed` phycological reaction which could be deemed as bad UX.

To close this issue - make sure the usage of utf-8 red ticks is only when an error happens or at minimum don't use them when doing a `dm cluster init`

**Comment by lukemarsden** [comment]
@binocarlos I would go ahead and make this change if you're up for it

**Comment by binocarlos** [comment]
@lukemarsden ack - will pick this up after the ops push 👍

**Comment by binocarlos** [comment]
I've removed the utf-8 characters and the output now looks like:

```
Checking suitable Docker is installed... assuming post-semver Docker client is sufficient.
assuming post-semver Docker server is sufficient.
Checking dotmesh isn't running...
  * dotmesh-etcd: is running
  * dotmesh-server: is running
  * dotmesh-server-inner: is running
done.
Pulling dotmesh-server docker image...
```

and:

```
Checking suitable Docker is installed... assuming post-semver Docker client is sufficient.
assuming post-semver Docker server is sufficient.
Checking dotmesh isn't running...
  * dotmesh-etcd: is not running
  * dotmesh-server: is not running
  * dotmesh-server-inner: is not running
done.
Pulling dotmesh-server docker image...
```
