### ISSUE TITLE
dm log intermittently fails with an error message

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#339]
This occurs especially on the backup job as it does a `dm log` on each branch on each dot in the cluster to back up it's contents.

```
priya@Priyas-MBP:~/dmesh/ops/backup$ dm log
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"Snapshots of '3c8919fc-27fb-4ca7-5837-5e91ac43cac5' not currently known on server '2a1f51b88403779'","data":null},"id":4037200794235010051}
' yields error Snapshots of '3c8919fc-27fb-4ca7-5837-5e91ac43cac5' not currently known on server '2a1f51b88403779'
```

**Comment by prisamuel** [comment]
comments from @lukemarsden 
this probably has to do with the asynchronous replication not working
or the fact that API calls to list dots should look at the master's snapshot list

**Comment by prisamuel** [comment]
*Only occurs on a multi node cluster on doing a `dm log` on a branch which has no commits on it.*

**Comment by prisamuel** [comment]
A very happy backup run just took place from the dothub into a local two node cluster AND into the two node backup cluster. Nice work @lukemarsden @binocarlos  A lot of dots that failed to push have now completed successfully. 

There was an instance of https://github.com/dotmesh-io/dotmesh/issues/336 on backing up zfs-kernel-modules.

**Comment by lukemarsden** [comment]
This is important enough that we should do a quick 0.3.2 release

**Comment by lukemarsden** [comment]
Done
