### ISSUE TITLE
We should remove not-useful but very noisy log messages for dotmesh-server-inner

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#340]
Using `grep -v 'getOne\|starting for\|notauth for\|POST /rpc\|AllDotsAndBranches\|opentracing'` the output of the `dotmesh-server-inner` container is **much** more useful.

We should just remove these log messages as they are not actually helping and means we can actually see what is happening in production and not fill up disks with those not useful logs.

**Comment by binocarlos** [comment]
I've added this function in `utils.go` that means we can still print these messages if we turn on the `PRINT_QUIET_LOGS` env var which will default to empty therefore quiet logging:

```go
func quietLogger(logMessage string) {
	if os.Getenv("PRINT_QUIET_LOGS") != "" {
		log.Printf(logMessage)
	}
}
```

In the cases where a log will be made quiet - I've changed `log.Printf` to `fmt.Sprintf` so the string can be passed forward to the function:

```go
quietLogger(fmt.Sprintf("[getOne] starting for %v", fs))
```

**Comment by binocarlos** [comment]
I've disable the zipkin middleware if `TRACE_ADDR` is empty - this should make the `error encountered while trying to extract span` errors not be logged anymore in production

**Comment by binocarlos** [comment]
I've added a `PRINT_HTTP_LOGS` variable which defaults to empty meaning the not very useful `POST /rpc HTTP/1.1` will not show up by default

This controls:

```go
if os.Getenv("PRINT_HTTP_LOGS") != "" {
  loggingRouter := mux.Router(handlers.LoggingHandler(getLogfile("requests"), router))
  err = http.ListenAndServe(fmt.Sprintf(":%s", SERVER_PORT), loggingRouter)
} else {
  err = http.ListenAndServe(fmt.Sprintf(":%s", SERVER_PORT), router)
}
```

**Comment by lukemarsden** [comment]
cool, it would be more common to do log levels, but this works :)

**Comment by binocarlos** [comment]
@lukemarsden good point I should have remembered log levels - otherwise `PRINT_X_LOGS` turns into a massive list - ding, my brain just turned back on :-)
