### ISSUE TITLE
Make `dotmesh-server` support putting the pool in a PV

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#342]
Add some logic to `require_zfs.sh` to support, when run under Kubernetes, creating a pool-in-a-file in a PV that's mounted into the container.

- Make it a small amount (1MiB?) smaller than the PV.
- Put a `README` alongside it saying what it is.
- Write the resulting pool ID into the README so we can get it without having zpool tools around, for fixing broken things in awkward situations.
- Never use any global names for pools etc, under the assumption that multiple instances of us may be running at any one time.

**Comment by alaric-datamesh** [comment]
This is part of epic #100

**Comment by alaric-datamesh** [comment]
See notes from #333, where we proved this possible.

**Comment by lukemarsden** [comment]
Remaining issue https://github.com/dotmesh-io/dotmesh/issues/348
