### ISSUE TITLE
Write a basic Dotmesh Operator that replicates our current DaemonSet setup

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#344]
This is part of epic #385 .

With #343 done, we can write a simple Dotmesh Operator that runs Dotmesh on every node in the cluster.

This can become the canonical way of running DM in k8s once documented!

**Comment by lukemarsden** [comment]
Per https://github.com/dotmesh-io/dotmesh/issues/343#issuecomment-376084231, we don't have a StatefulSet template per se, but we do have a [design](https://docs.google.com/document/d/1OTTk8pmxWYQ6L4YN6v14OrGKXn_zSWTfCaaWGObvsrQ/edit#heading=h.e7p46kxrsqpi) for an operator which will set up PVCs, node labels etc appropriately!

**Comment by lukemarsden** [comment]
As part of this issue, we need a testing strategy.

We are going to develop simple `dind-flexvolume` and `dind-dynamic-provisioner` modules which can be used to simulate cloud provider volumes (insofar as they provide writeable filesystems which dotmesh can initialize zfs pools on) in the dind tests.

Then we can write dind tests for consuming PVCs from a `dind` storageclass and providing dotmesh PVs.

Later, we'll be able to simulate killing a dotmesh node and having the PV failover and "reattach" to a different dind.

**Comment by lukemarsden** [comment]
Note that some of the above plan spans different github issues!

**Comment by lukemarsden** [comment]
In particular "pool of dotmeshes" depends on #341, #345 and ...

**Comment by lukemarsden** [comment]
see https://kubernetes.io/blog/2018/01/introducing-client-go-version-6 `Updating dependencies – golang/dep`

**Comment by alaric-datamesh** [comment]
I'm moving the "extra work" out into a new epic which this is just the first part of. This is now part of epic #385, which is a sub-epic of #100!

**Comment by alaric-datamesh** [comment]
This is in production, so I'm calling it done.
