### ISSUE TITLE
Make `require_zfs.sh` come up with a pool name itself

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#348]
This is part of epic #100 

To allow for a statefulset that happens to put two dotmesh servers on the same node, we need to use unique ZFS pool names.

We could do that in `require_zfs.sh` like so:

1. In the case of creating a new pool-in-a-file, pick a random UUID-y name (prefixed with `dotmesh-`) for it and set `$POOL` to that. Also, write it to `$DIR/dotmesh_pool_name`.
2. In the case where `$FILE` already exists, set `$POOL` to the contents of `$DIR/dotmesh_pool_name` if it exists - and `pool` if not, for backwards compatibility.
3. Stop passing in `USE_POOL_NAME` from yaml and `dm cluster init` as it's now vestigial when `USE_POOL_DIR` is set.
4. Update docs.

**Comment by alaric-datamesh** [comment]
For point (3), not that if `USE_POOL_NAME` is set and `USE_POOL_DIR` is not, we'll try and use an existing pool called `$USE_POOL_NAME` - check we don't break this functionality, and make it clear in the docs where we currently talk about having to create a pool called `pool`!

**Comment by lukemarsden** [comment]
We could also check for `dotmesh-pool` as that's a better name to document creating manually for users who want manual control over pool layout on their block devices.

**Comment by alaric-datamesh** [comment]
This is now being subsumed by the operator work in epic #385 - the operator will pick the pool name and feed it to `require_zfs.sh`! This is a better idea, as it can also use the pool name as the PVC (and hence PV) name, for better observability of the system. If it's picked in `require_zfs.sh`, then the operator doesn't know it in advance.
