### ISSUE TITLE
dm command line tools to view (and hack) replication status

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#353]
As developers working on #352 and as users wanting to tinker with the replication state in their cluster (generally as part of adding/removing/dealing with failed nodes), I would like to be able to tell what commits of a branch are replicated to which nodes in my cluster, and to be able to force another node to be the master for a branch. A particular use case for this forcing is when the node that is master has permanently died, and we need to make another node master (abandoning any state left on the old master) so the branch can be used again.

This is in two parts.

To view the replication state of a branch, we can access the `/dotmesh.io/servers/snapshots/SERVER/BRANCH` cache in etcd. A useful way of displaying this would be to find the list of snapshots that *aren't* on every server, and for each server, record which snapshots it's missing. We can also state which server is the master for this branch.

To re-master a branch, we normally just want any active node to become the master, so can let the system pick one at random (perhaps the node that the RPC request lands on); but the ability to force a specific node will be useful in development/testing so should be available.

**Comment by lukemarsden** [comment]
This was implemented in `dm dot show`.
