### ISSUE TITLE
Old etcd operator - 0.5

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#354]
We are using the etcd operator from about a year ago and there are a bunch of [releases](https://github.com/coreos/etcd-operator/releases) since then - let's upgrade the version of the operator we are running both for users and in the dothub

**Comment by prisamuel** [comment]
This would also upgrade etcd to use hostdir instead of empty dir.

**Comment by prisamuel** [comment]
If an upgrade doesn't really help us with both the issues above. Check out https://github.com/kopeio/etcd-manager

**Comment by binocarlos** [comment]
> This would also upgrade etcd to use hostdir instead of empty dir.

it turns out the answer to this is no - it still uses emptyDir for operator version: 0.8.4

The manifests for version `0.8.4` are now is master
