### ISSUE TITLE
Bad UX for wrong api key entry

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotmesh#356]
A user entered the wrong api key for their clusters and the error response was:

```
dm remote add gke admin@$NODE_IP
API key:
Unable to connect to any of the addresses attempted: [{Scheme:http Hostname:X.X.X.X Port:32607} {Scheme:http Hostname:X.X.X.X Port:6969}], errs: [Permission denied. Please check that your API key is still valid. Post http://X.X.X.X:6969/rpc: dial tcp X.X.X.X:6969: i/o timeout]
```

This triggered the user to go down a network debugging path because the error message is not clear.

Proposal: if we get a confirmed `bad password` response from any of the servers - print a message that says: `the api key was rejected - please check it and try again` (or something)

In the case we have a genuine network connection failure - print the message above

**Comment by prisamuel** [comment]
We want to distinguish between n/w errors and API errors.
