### ISSUE TITLE
make everything that consults the list of dots in the system be consistent

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#364]
e.g. `DotmeshRPC.List` and anything else that enumerates things

* look in the same place (suggest the registry)
* be tolerant of things being inconsistent e.g. between mastersCache, fsMachines and the registry

**Comment by lukemarsden** [comment]
a nice consequence of doing this is dramatically simplifying the `List` code and probably speeding it up as well (currently it seems to fetch all branches and clobber top level filesystems for each branch).

**Comment by alaric-dotmesh** [comment]
Done as part of #489
