### ISSUE TITLE
Auto push all commits to mirror into another cluster.

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#370]
This is to provide us with a feature that can be used for backing up the dots in the production cluster to the backup cluster. https://github.com/dotmesh-io/ops/issues/40

More details on the roadmap item here:
https://github.com/dotmesh-io/roadmap/issues/17

**Comment by lukemarsden** [comment]
This will need to tolerate the case where there's two filesystems with the same name but different IDs between the clusters. Probably by renaming the dot on the target cluster.

**Comment by lukemarsden** [comment]
Also related: https://github.com/dotmesh-io/roadmap/issues/37

**Comment by Godley** [comment]
Think this is no longer relevant as we are working for data science not devops
