### ISSUE TITLE
Debug introspection for Dotmesh servers

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#384]
As a dotmesh support person, I'd like to know what the in-memory state of a dotmesh server process is, so that I can diagnose related problems.

When things go awry in a running Dotmesh server, our first port of call is to inspect etcd for the global state; but when we suspect that the problem lies in local state, we need to find out what's in memory on a particular node.

So we should add a debug API call that reports:

1. When the fetchAndWatchEtcd watch last received an update from etcd
 (by updating a timestamp in memory whenever anything is read from etcd and piped into the dispatcher this would tell us if nodes are getting blocked on reading from etcd somehow)
2. What state each fsMachine is in and how long it's been there. There are certain "home" states which are normal to spend a lot of time in: missing, inactive, active. Spending long periods of time in other states indicates that something is getting stuck and is suspicious. Or that very long transfers are underway (e.g. pushPeerState might be receiving gigabytes of data).
3. Everything else that the system knows! e.g. the contents of all of the registry, the global caches, the fsMachine map and anything else stored in the `InMemoryState`. This would help us diagnose mismatches between e.g. the etcd state. Hopefully inspecting the caches wouldn't get caught on any locks being erroneously held - we could try to read them with a timeout, and if the timeout fails, report that fact.
4. The etcd state (by asking etcd).
5. Stack traces.
6. Version of dotmesh.

It can be called via the `dm debug` command line for now; development of higher-level tools can be a future issue (see https://docs.google.com/document/d/1lpPYDYSgHhBTbpLbPwjhPwlh559h2759aoED4a3Fvug/edit for some thoughts)

**Comment by lukemarsden** [comment]
c'est fini, non?

**Comment by alaric-datamesh** [comment]
.i go'i .i ti se fanmo .ui
