### ISSUE TITLE
dm pull  fails.

### ISSUE THREAD

**Issue by MahipalRao** [dotmesh-io/dotmesh#395]
Tried dotmesh while pulling, got this error

$dm pull hub moby_counter branch_a
Pulling admin/moby_counter from hub:Mahipal/moby_counter
Calculating...
Awaiting transfer... 
error 9.50 KB / 9.50 KB [============================] 100.00% 11.39 MiB/s (1/2)
error: Response event != finished-{push,pull} or peer-up-to-date: <Event maximum-retry-attempts-exceeded: responseEvent: <Event get-failed-pull: err: exit status 1, filesystemId: b9575fe9-d4ab-4025-4ab9-edd0894d4195>>
Response event != finished-{push,pull} or peer-up-to-date: <Event maximum-retry-attempts-exceeded: responseEvent: <Event get-failed-pull: err: exit status 1, filesystemId: b9575fe9-d4ab-4025-4ab9-edd0894d4195>>
Response event != finished-{push,pull} or peer-up-to-date: <Event maximum-retry-attempts-exceeded: responseEvent: <Event get-failed-pull: err: exit status 1, filesystemId: b9575fe9-d4ab-4025-4ab9-edd0894d4195>>
List of from dm is 
$ dm list
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

  DOT           BRANCH  SERVER            CONTAINERS  SIZE       COMMITS  DIRTY
* apples        master  a1fbbad082866d3c              19.00 kiB  0        19.00 kiB  
  moby_counter  master  a1fbbad082866d3c              9.00 kiB

**Comment by alaric-datamesh** [comment]
This works fine for me - it might have been a transient problem, and we've just done a lot of work to improve the reliability of push/pull in general that might have fixed this. Please can you try again, and reopen the issue if it's still broken? Thanks!
