### ISSUE TITLE
Operator: PV-per-node mode

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#401]
This is part of epic https://github.com/dotmesh-io/dotmesh/issues/385

As a kubernetes user, I'd like to be able to configure Dotmesh to use PVs for pool storage on each node, so I can get the desirable resilience properties of PVs in cloud environments.

Sample ConfigMap contents for this mode, showing what we'd like configurable:

```
storageMode: pvPerNode
pvPerNode.pvSizePerNode: 100G
pvPerNode.storageClass: fast
```

The operator, in this mode, will need to create PVCs with the desired size and storageClass, and attach them to the Dotmesh server pods at a suitable path. `require_zfs.sh` then needs to create a pool file of the desired size (minus a small fraction for FS metadata) in that path. Be careful of whether paths are in container or host namespaces!

The operator needs to pick a name for the pool, which the PVC should be named after, and the Dotmesh pod should be named after (instead of using the hostname), and be used as the ZFS pool name (to pave the way for multiple pools on the same host).

While we're at it, make `require_zfs.sh` put a README.txt file alongside the pool file, listing the pool name, the version of the server that created it, and so on.

**Comment by prisamuel** [comment]
General observation on PVPerNodeMode: GKE cloud PV's take a long time to detach and re-attach to other nodes. When the operator restarted failed pods, they often run into this issue:

```
  Warning  FailedMount  1m (x490 over 18h)  kubelet, gke-cluster-backup-default-pool-c853a60c-70gq  Unable to mount volumes for pod "server-pvc-5f35a597e1983512-node-gke-cluster-backup-default-pool-c853a60c-70gq_dotmesh(a7276943-6ff8-11e8-b661-42010aa40059)": timeout expired waiting for volumes to attach/mount for pod "dotmesh"/"server-pvc-5f35a597e1983512-node-gke-cluster-backup-default-pool-c853a60c-70gq". list of unattached/unmounted volumes=[backend-pv]
```

**Comment by prisamuel** [comment]
Current list of [Problems with ZFS in a k8s PV](https://docs.google.com/document/d/1uuaE5WZux8XAJ5QP67peY7SXoIAaNG2OaDorhd5vjCw/edit#heading=h.tgnv0snuiu07)

**Comment by alaric-dotmesh** [comment]
We're going to call this "done", even though it has issues, as the issues are really bugs - and ones to do with the interaction of Kubernetes and ZFS that we just need to find ways to work around!

See #463 for the rest of this work.
