### ISSUE TITLE
Make the smoke tests run every hour

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#402]
This is a refugee from https://github.com/dotmesh-io/dotmesh/issues/17

Make gitlab run the smoke tests (latest on master?) every hour, to check that dothub is accepting pushes OK.

**Comment by lukemarsden** [comment]
We now have a schedule for running the smoke tests: http://gitlab.dotmesh.io:9999/dotmesh/dotmesh-sync/pipeline_schedules
