### ISSUE TITLE
Monitor and fix our own dogfooding jobs

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#408]
Cronjobs to monitor for failures
- [ ] ZFS builder jobs
- [ ] etcd-backup jobs

**Comment by alaric-datamesh** [comment]
How do we monitor these? Ideally, I want an alert every time a job pod terminates in an `Error` state. I can't find anything off-the-shelf to do that. Do we need to write our own?!

**Comment by alaric-datamesh** [comment]
Seems we might need to write a thing: a Kubernetes Job Failure Operator

1. Fetch all, and then watch, jobs (matching a configurable selector).
2. For each job, if any of its pods are in the Error state and the job doesn't have the "already processed" flag set, issue an alert (configurable HTTP endpoint), and set the "already processed" flag.

**Comment by alaric-datamesh** [comment]
Apparently (see Twitter thread) this can be done with Prometheus, without needing to alert on error rates or some such (eg, one alert per failure, citing the failed pod ID) - let's learn how to do that!

**Comment by alaric-dotmesh** [comment]
Now part of https://github.com/dotmesh-io/ops/issues/61
