### ISSUE TITLE
Does `dm dot show`'s branch list show replication status only for the master?

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#414]
Priya did a `dm dot show` on a diverged dot, and it always shows the same state for the master and diverged branches.

Is `dm dot show` always showing the master branch state, but claiming to be showing the state for each branch?

(While fixing this, it might also be easy to print out the branch FSIDs in `dm dot show` which would be nice)

**Comment by prisamuel** [comment]
As suspected there was an issue here. We report the master dot's server status for all branches https://github.com/dotmesh-io/dotmesh/blob/7ee9b45a9ad4d121965d6262f25d93b6099b6c75/cmd/dm/pkg/commands/dot.go#L371
