### ISSUE TITLE
memory leak (affecting Dotscience)

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#422]
dotscience prototype (and `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` on docker for mac, then running `top`) shows that `dotmesh-server` is leaking memory and then getting OOM'd.

**Comment by prisamuel** [comment]
We are memory leaking on production as well. We see it on the backup cluster as we don't CI to it (restart it).
![gce vm instance - memory utilization for backup](https://user-images.githubusercontent.com/151395/40551502-060e470c-6035-11e8-900c-a788c8e09c45.png)

**Comment by prisamuel** [comment]
Suspicion is that etcd is leaking client connections during error cases in FetchAndWatchEtcd.
https://github.com/dotmesh-io/ops/issues/64#issuecomment-394680936

**Comment by alaric-dotmesh** [comment]
I've fixed two goroutine leaks, one of which would have been affecting production (2 gr's leaked for every deleted filesystem); I'll look at the etcd connection issue next, then we'll just have to wait and see if production memory usage stabilises to know if there's other issues afoot.

**Comment by alaric-dotmesh** [comment]
I don't think we're abusing etcd connections.

Evidence:

1. Reading the etcd client library source from the vendor directory, the KeysAPI is just a thin wrapper providing a high-level API around the Client, which does all the actual network calls; we create a lot of KeysAPI instances, which is unneessary and I'll reduce that, but they all share a single Client.
2. lsof in a `dotmesh-server-inner` container after running `TestSingleNode` shows only two open TCP connections to port `42379`, despite having called `getEtcdKeysApi` 6,793 times.

So, I'll try and make us share a single KeysAPI to reduce the gc pressure of allocating so many of them (even though they're tiny) as they seem perfectly safe to share between goroutines, then I'll close this issue - we can reopen it if more evidence of memory leaks in production or dotscience are seen.
