### ISSUE TITLE
support specifying port in dm client

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#428]
to talk to dotmesh on an alternate port

could be `foo:1234`

@justincormack would like this to help with testing dm-linuxkit by running two dotmeshes

**Comment by Godley** [comment]
Wondering whether this needs to be client only or on the server side? I'd have presumed it needs to be both in order for it to work. 

If it needs to be server side, there's a hard coded port number in `./require_zfs.sh` which will need to be customisable, presumably by passing it to `dm cluster init` - suppose I'd do that by having that command pass another env variable to the `dotmesh-server` container which is then read inside `./require_zfs.sh` is ran.

**Comment by lukemarsden** [comment]
It will need to touch the server side too, since the use case here is push/pull between two clusters on the same host.

**Comment by binocarlos** [comment]
actually - the comment above ignores `require_zfs.sh` - it might be better to add a port map into that script
