### ISSUE TITLE
Ensure transfers (and any other long-term operations) are rename-safe

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#43]
A volume could be renamed while transfers are in progress. This should be fine if, after setting up the transfer, everything is done in terms of volume UUIDs, but we're not sure if this is the case.

In general: Do all volume name resolution at the start of any operation, and use UUIDs thereafter, to avoid renames breaking in-progress things.

In particular: Do an audit of the code to ensure this is the case for already-written things.

**Comment by rusenask** [comment]
Edge case
