### ISSUE TITLE
add timeout to Ping call

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#430]
most RPC calls, like Ping, ought to respond quickly. if they don't, perhaps we've hit a mysterious window during kubernetes setup where TCP connections end up in a black hole and timeout forever. this is causing issues in CI.

**Comment by prisamuel** [comment]
Seeing more of these in the tests. We can add timeouts at various levels in the application. 

- Client side request timeouts: Adding timeouts to 'dm' commands is pretty easy with golang context/channels but this will only timeout requests when users/tests are using the specific client that implements timeouts. This covers a multitude of network issues as the timeout starts from the time the request is sent out. However each client would have to implement it's own timeout logic (python, golang, JS libs). Seems to best fit the requirement at the moment.

- Server side timeouts: There are two areas in which server side timeouts can be implemented.
a) Method level timeouts: Timeouts are implemented in each method i.e when it does external calls and timeouts are returned as any other error. Seems fairly suitable for our use case, but will mean quite a lot of duplication if ALL RPC methods require sensible timeouts.

a) Middleware timeouts: Adding sensible timeouts within a middleware is common, however less suitable for us as the same blanket timeout does to apply to all RPC calls.
