### ISSUE TITLE
Dotmesh doesn't work / breaks docker on uninstall

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#434]
From user feedback-

Hi Luke,

I really love the concept. Below is my experience from a few weeks back in case it helps.<br>
First impression was that dotmesh cluster was going to be smart enough to inject into a docker compose setup. However, I later realised that I needed to manually introduce volume plugin into my existing docker compose which took a bit of the shine off.
After trying to insert the volume plugin into a relatively vanilla MySQL setup in a docker composite stack and having it fail to startup the containers, I decided to uninstall.
After uninstall, it left a lot of junk around and broke my docker setup which took quite a while to get to the bottom of.
I hope this information is useful for improving your software and I'd be happy to try it again in a more stable version in the future.
Good luck with what you are doing, I think it is a really great idea and I have not found any tools that can nail this problem of simplifying container state management yet.

Cheers,
(redacted)

**Comment by alaric-dotmesh** [comment]
Let's attempt to recreate this, as there's a bunch of details we'd like to know (does @luke have contact details for the original poster so we can ask questions?)

**Comment by lukemarsden** [comment]
Conversation is in Intercom

**Comment by rusenask** [comment]
Not relevant to current dotscience setup
