### ISSUE TITLE
[good first issue] Common go library for API tools

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#44]
We should make a library that can be used from everywhere that needs it; it should be a proper Go SDK with the following properties:

- Nicely object-oriented design, calling API methods on a "Dotmesh Cluster" object
- Encapsulates the transfer logic, where a transfer request is set up and then its status polled (currently in `cmd/dm/pkg`); set up a go channel to push in a cancellation, and one which is used to push progress updates back.
- Types used in the API (such as `DotmeshVolume`) should be defined in the client library and not duplicated elsewhere in any of our repos (in particular, the RPC server in `cmd/datamesh-server/pkg/main/rpc.go` should reference the definition from the go library as well).

Existing duplicated code needs to be refactored out into the library, so that we use the go library ourselves. Any code that contains the string `DotmeshRPC` is quite likely an API user (apart from `cmd/datamesh-server/pkg/main/rpc.go`...)

**Comment by lukemarsden** [comment]
This should be the same type of thing as https://github.com/dotmesh-io/python-sdk

**Comment by lukemarsden** [comment]
first pass made in github.com/dotmesh-io/dotmesh/pkg/client :sparkles:
