### ISSUE TITLE
Mismatched ZFS versions cause crashes (was: coredump on predicting size when cloning from dotmesh on ubuntu 18.04)

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#440]
<img width="1792" alt="screen shot 2018-06-07 at 12 09 37" src="https://user-images.githubusercontent.com/264658/41120919-d84a1d20-6a4b-11e8-9278-1b98830c58b7.png">

probably because of kernel/userland mismatch

**Comment by lukemarsden** [comment]
Need to detect zfs kernel version and provide appropriate userland tools for dotmesh to use.

Also look into libzfs_core, but don't burn lots of time on it

**Comment by lukemarsden** [comment]
we can use `modinfo -F version zfs` to detect the kernel version
to get the bionic userland tools (0.7 ZoL branch) working we really need a bionic production image though...

**Comment by alaric-dotmesh** [comment]
Proposal: Have multiple ZFS toolsets in different directories, then in all zfs commands run them like this:

`LD_LIBRARY_PATH=$ZFS/lib $ZFS/bin/[zpool|zfs] ...`

**Comment by lukemarsden** [comment]
This is needed for #519

**Comment by alaric-dotmesh** [comment]
Done!
