### ISSUE TITLE
Handle unrecoverable errors with a 'failedState'

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotmesh#450]
We see quite a lot of statemachines that go into a loop of trying to recover and fail when faced with an unrecoverable error. This causes an avalanche effect when the master node goes into a fs loop, and the other nodes go into a similar receiving/calculating loop as well. 

In order to fix this we have the following plan:
- [x] Introduce a failedState in addition to the backOff state, where when an fs encounters an unrecoverable error such as in `discoveringState()` where it does `f.state.alignMountStateWithMasters(f.filesystemId)` it goes into a failedState. Another candidate that could possibly lead to failedState is mount failures.

- [ ] When in a failedState the fsmachine updates etcd that no snapshots are available, this would stop other nodes from trying to receive new snapshots from this fs.

- [ ] Add an internal RPC to unwedge an fsMachine from failedState to go into discovering. The main difference between a backOffState and a failedState is that when an fs goes into failedState it does not sleep for a short period and try again. The internal RPC is intended to make manual intervention easier.

**Comment by lukemarsden** [comment]
Discovered that `missing` -> `receiving` -> NoFromSnaps case -> `discovering` was a hard-loop, so introduced a backoff to slow things down ^

**Comment by lukemarsden** [comment]
The root cause of this is that you can't `mount.zfs` a filesystem which is mounted in _any_ namespace. Make failed attempts to mount attempt to unmount from the root namespace and retry before aborting.

**Comment by lukemarsden** [comment]
Managed to fix this by getting everything out of failed state with the commits above. Leaving failed state in the code as it's a useful thing to be able to look for in the `ops/diagnostics/log-mangling` tools.
