### ISSUE TITLE
Tool to automatically make docker compose files use dotmesh for volumes

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#458]
Given a docker compose, make the requisite changes to add dotmesh volumes. (Maybe auto detect common unvolumed containers like MySQL and postgres etc.)

Same with kube yaml - just add the requisite storage classes.

**Comment by lukemarsden** [comment]
Usage could be `dotmeshify docker-compose.yml | docker-compose up -f - -d`

**Comment by lukemarsden** [comment]
Or `docker-compose up -f $(dotmeshify docker-compose.yml)`

**Comment by Godley** [comment]
Reopen when needed/requested, no time to do this right now
