### ISSUE TITLE
Dotmesh pods not starting on kubeadm on aws

### ISSUE THREAD

**Issue by datacabinet** [dotmesh-io/dotmesh#465]
On Centos 7

```
I0625 21:25:28.933712       1 main.go:369] Starting Dotmesh Operator version release-0.5.4
I0625 21:25:29.234451       1 main.go:471] Labelling unfamiliar node ip-172-20-0-230.us-west-2.compute.internal so we can bind a Dotmesh to it
I0625 21:25:29.253011       1 main.go:471] Labelling unfamiliar node ip-172-20-0-96.us-west-2.compute.internal so we can bind a Dotmesh to it
I0625 21:25:30.270464       1 main.go:1002] Creating pod server-ip-172-20-0-96.us-west-2.compute.internal running quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a on node ip-172-20-0-96.us-west-2.compute.internal
I0625 21:25:30.295779       1 main.go:1002] Creating pod server-ip-172-20-0-230.us-west-2.compute.internal running quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a on node ip-172-20-0-230.us-west-2.compute.internal
I0625 21:25:54.429963       1 main.go:604] Observing pod server-ip-172-20-0-230.us-west-2.compute.internal - status Failed: FAILED (Message: ) (Reason: )
I0625 21:25:54.429997       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:25:54.430029       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"Ready", Status:"False", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"ContainersNotReady", Message:"containers with unready status: [dotmesh-outer]"}
I0625 21:25:54.430044       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:25:54.430059       1 main.go:614] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - container v1.ContainerStatus{Name:"dotmesh-outer", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(0xc4200df1f0)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:false, RestartCount:0, Image:"quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a", ImageID:"docker-pullable://quay.io/dotmesh/dotmesh-server@sha256:6b468bdc8310405100ed06ccf06e409a589c34f8dce27e702376f8227a0aa2db", ContainerID:"docker://75176f33f91c824c917b805e319804015d35a438a12d8c62591d4e828e05b62b"}
I0625 21:25:54.430092       1 main.go:685] Deleting pod server-ip-172-20-0-230.us-west-2.compute.internal
I0625 21:25:54.959406       1 main.go:726] Not creating a pod on undotted node ip-172-20-0-230.us-west-2.compute.internal, as the old pod is being cleared up
I0625 21:25:55.959608       1 main.go:604] Observing pod server-ip-172-20-0-96.us-west-2.compute.internal - status Failed: FAILED (Message: ) (Reason: )
I0625 21:25:55.959633       1 main.go:611] Failed pod server-ip-172-20-0-96.us-west-2.compute.internal - condition v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:25:55.959661       1 main.go:611] Failed pod server-ip-172-20-0-96.us-west-2.compute.internal - condition v1.PodCondition{Type:"Ready", Status:"False", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"ContainersNotReady", Message:"containers with unready status: [dotmesh-outer]"}
I0625 21:25:55.959673       1 main.go:611] Failed pod server-ip-172-20-0-96.us-west-2.compute.internal - condition v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558730, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:25:55.959684       1 main.go:614] Failed pod server-ip-172-20-0-96.us-west-2.compute.internal - container v1.ContainerStatus{Name:"dotmesh-outer", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(0xc4200dfb90)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:false, RestartCount:0, Image:"quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a", ImageID:"docker-pullable://quay.io/dotmesh/dotmesh-server@sha256:6b468bdc8310405100ed06ccf06e409a589c34f8dce27e702376f8227a0aa2db", ContainerID:"docker://e4b2a3eded008e3910d7d7f1a0cb6724d8427d5b6ec6fd3300e37546a6af0f59"}
I0625 21:25:55.959712       1 main.go:685] Deleting pod server-ip-172-20-0-96.us-west-2.compute.internal
I0625 21:25:56.180479       1 main.go:726] Not creating a pod on undotted node ip-172-20-0-96.us-west-2.compute.internal, as the old pod is being cleared up
I0625 21:25:56.180513       1 main.go:1002] Creating pod server-ip-172-20-0-230.us-west-2.compute.internal running quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a on node ip-172-20-0-230.us-west-2.compute.internal
I0625 21:25:57.513183       1 main.go:1002] Creating pod server-ip-172-20-0-96.us-west-2.compute.internal running quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a on node ip-172-20-0-96.us-west-2.compute.internal
I0625 21:26:00.922816       1 main.go:604] Observing pod server-ip-172-20-0-230.us-west-2.compute.internal - status Failed: FAILED (Message: ) (Reason: )
I0625 21:26:00.922841       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"Initialized", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558756, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:26:00.922865       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"Ready", Status:"False", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558756, loc:(*time.Location)(0x187b440)}}, Reason:"ContainersNotReady", Message:"containers with unready status: [dotmesh-outer]"}
I0625 21:26:00.922878       1 main.go:611] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - condition v1.PodCondition{Type:"PodScheduled", Status:"True", LastProbeTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63665558756, loc:(*time.Location)(0x187b440)}}, Reason:"", Message:""}
I0625 21:26:00.922888       1 main.go:614] Failed pod server-ip-172-20-0-230.us-west-2.compute.internal - container v1.ContainerStatus{Name:"dotmesh-outer", State:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(0xc420258770)}, LastTerminationState:v1.ContainerState{Waiting:(*v1.ContainerStateWaiting)(nil), Running:(*v1.ContainerStateRunning)(nil), Terminated:(*v1.ContainerStateTerminated)(nil)}, Ready:false, RestartCount:0, Image:"quay.io/dotmesh/dotmesh-server:bd09ac301a70bfe2a4669900fa23330844caa77a", ImageID:"docker-pullable://quay.io/dotmesh/dotmesh-server@sha256:6b468bdc8310405100ed06ccf06e409a589c34f8dce27e702376f8227a0aa2db", ContainerID:"docker://1b72ec2ad67625224fade3e3bb9b517caf8ea49ca1783b4c591d323e968ea759"}
```

**Comment by alaric-dotmesh** [comment]
Hrm, I think I need to add more logging to find out why these pods are failing, as they're not leaving a useful message. Watch this space...

**Comment by datacabinet** [comment]
Please let me know and I will update dotmesh and try.

**Comment by alaric-dotmesh** [comment]
Hi there! I've built a version with the new logging in, which is available at https://get.dotmesh.io/unstable/465-operator-logging/ - you'll want the YAML files in `https://get.dotmesh.io/unstable/465-operator-logging/yaml/dotmesh-k8s-1.8.yaml` and so on (just follow the normal upgrade instructions, but use `https://get.dotmesh.io/unstable/465-operator-logging/yaml` where you'd normally use `https://get.dotmesh.io/yaml` in the URLs).

It should put a lot more stuff in the logs of the dotmesh-operator deployment - if you can send us what it emits, I can take a look and try to figure out what it's unhappy about!

Thanks!

**Comment by datacabinet** [comment]
HI Alaric, Please give us a few days and we will try again. We are busy with a release.

**Comment by lukemarsden** [comment]
hey @datacabinet any chance you could take a look at this please? If you need help, jump on Slack and ping me and I'll help you out :)

**Comment by datacabinet** [comment]
We are extremely sorry for going silent. We are trying to do a release and
struggling with some last minute bugs.

We want to move to k8s asap and would love to get to work with your team.

Regards

**Comment by lukemarsden** [comment]
No worries - looking forward to collaborating. I'll close this issue for now, but please re-open it as soon as you're ready.

**Comment by absk82** [comment]
I deployed using the new files and I could see some pods active in dotmesh namespace, but one of them(server-ip-172-18-0-163.us-west-2.compute.internal) stayed in ContainerCreating state for ever. 

root@ip-172-20-0-160:/app# kubectl get pods -n dotmesh
NAME                                                READY     STATUS              RESTARTS   AGE
dotmesh-dynamic-provisioner-5994f8b745-gvtz9        1/1       Running             0          1d
dotmesh-etcd-cluster-m89wlb22jl                     1/1       Running             0          1d
dotmesh-etcd-cluster-p8bj9lt82q                     1/1       Running             0          1d
dotmesh-etcd-cluster-tqcnzwq7jl                     1/1       Running             0          1d
dotmesh-operator-67d6bc7c66-plgcc                   1/1       Running             0          1d
etcd-operator-7b8496785f-7tz6l                      1/1       Running             2          1d
server-ip-172-18-0-163.us-west-2.compute.internal   0/1       ContainerCreating   0          2s
server-ip-172-18-0-173.us-west-2.compute.internal   0/1       Terminating         0          4s




Here is what I see in master's journalctl : 



10623]: INFO: 2018/08/13 16:06:53.960804 added entry 10.32.0.3 to weave-Q}x3s}=G;0?;)ye4bcpR/n^39 of e3aa0424-9f12-11e8-9787-022c98761ed4
10623]: [158B blob data]
10623]: curl: (22) The requested URL returned error: 404 Not Found
10623]: ZFS is not installed on your docker host, and unable to find a kernel module for your kernel: 3.10.0-693.21.1.el7.x86_64
10623]: Please create a new GitHub issue, pasting this error message, and tell me which Linux distribution you are using, at:
10623]: 
10623]:     https://github.com/dotmesh-io/dotmesh/issues
10623]: 
10623]: Meanwhile, you should still be able to use dotmesh if you install ZFS manually on your host system by following the instructions at http://zfso
10623]: 
10623]: Alternatively, Ubuntu 16.04 and later comes with ZFS preinstalled, so using that should Just Work. Kernel modules for Docker for Mac and other 
10623]: + echo 'ZFS is not installed on your docker host, and unable to find a kernel module for your kernel: 3.10.0-693.21.1.el7.x86_64'
10623]: + echo 'Please create a new GitHub issue, pasting this error message, and tell me which Linux distribution you are using, at:'
10623]: + echo
10623]: + echo '    https://github.com/dotmesh-io/dotmesh/issues'
10623]: + echo
10623]: + echo 'Meanwhile, you should still be able to use dotmesh if you install ZFS manually on your host system by following the instructions at htt
10623]: + echo
10623]: + echo 'Alternatively, Ubuntu 16.04 and later comes with ZFS preinstalled, so using that should Just Work. Kernel modules for Docker for Mac an
10623]: + exit 1
ped libcontainer container cfdd9485adad3270e44ee911414e1766abb16e382641c037ea9134d7470b7662.
[10018]: systemdhook <debug>: cfdd9485adad: Skipping as container command is /require_zfs.sh, not init or systemd
]: umounthook <debug>: cfdd9485adad: only runs in prestart stage, ignoring
10623]: time="2018-08-13T16:06:54.074017248Z" level=error msg="containerd: deleting container" error="exit status 1: \"container cfdd9485adad3270e44ee9
10623]: time="2018-08-13T16:06:54.074900982Z" level=warning msg="cfdd9485adad3270e44ee911414e1766abb16e382641c037ea9134d7470b7662 cleanup: failed to un
10623]: DEBU: 2018/08/13 16:06:54.521433 EVENT UpdatePod {"metadata":{"creationTimestamp":"2018-08-13T16:06:51Z","labels":{"dotmesh.io/role":"dotmesh-s
10623]: INFO: 2018/08/13 16:06:54.521468 deleting entry 10.44.0.13 from weave-+FPdY83%9%Hgj1MVl}gh(=3fA of e3a87a92-9f12-11e8-9787-022c98761ed4


Please let me know how to proceed.
