### ISSUE TITLE
After restarting dotmesh-server-inner, all dots go into "failed, never coming back"

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#466]
On Docker for Mac.
```
luke@dot:~/ps/dotmesh$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

```
luke@dot:~/ps/dotmesh$ dm version
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

Client:
        Version: master-07981dd
Server:
        Version: master-9f37cd3
```

I restarted dotmesh by deleting the inner container (so that the outer container would restart it)
```
docker rm -f dotmesh-server-inner
```
Some moments later, dotmesh-server-inner is back up but dotmesh has forgotten the size of everything, and thinks all the filesystems are doomed.
```
luke@dot:/Volumes/dotscience$ dm list
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

  DOT                                                               BRANCH  SERVER            CONTAINERS              SIZE  COMMITS  DIRTY
  48f4c68f414f0c6373343682f9b8e6bde0443ae8725aed56af261d20bae0d986  master  8d5737c4c51be30c  /samba                  -     0        -
  agent1                                                            master  8d5737c4c51be30c  /dotscience-app,/samba  -     0        -
  agent2                                                            master  8d5737c4c51be30c  /dotscience-app,/samba  -     0        -
* house-prices                                                      master  8d5737c4c51be30c  /dotscience-app,/samba  -     0        -
luke@dot:/Volumes/dotscience$ dm dot show house-prices
Dot admin/house-prices:
Master branch ID: b45cfa0a-5037-4389-6ea4-656d04185e57
Dot is currently selected.
Commits: 0
Dot size: - (all clean)
Branches:
* master (containers: master)
%!(EXTRA string=/dotscience-app,/samba)   Replication Status:
    server 8d5737c4c51be30c [MASTER] (status: failed: never coming back, 0 snaps (v0)) is up to date
```

There's also a spurious EXTRA there, some dodgy string formatting in `dm dot show`.

Log shows:

`
2018/06/26 01:47:50 [run:7eebca68-4ddc-4c28-4d0d-1683fa8e1f12] got resp: <Event failed-recovery-unmount: recovery-err: "exit status 1", recovery-combined-output: "umount: can't unmount /var/lib/dotmesh/mnt/dmfs/7eebca68-4ddc-4c28-4d0d-1683fa8e1f12: No such file or directory\n", original-err: "exit status 128", original-combined-output: "filesystem 'pool/dmfs/7eebca68-4ddc-4c28-4d0d-1683fa8e1f12' is already mounted\n">
`

`
2018/06/26 01:47:50 [discoveringState:b45cfa0a-5037-4389-6ea4-656d04185e57] error trying to align mount state with masters: Couldn't mount filesystem: <Event failed-recovery-unmount: original-err: "exit status 128", original-combined-output: "filesystem 'pool/dmfs/b45cfa0a-5037-4389-6ea4-656d04185e57' is already mounted\n", recovery-err: "exit status 32", recovery-combined-output: "umount: /var/lib/dotmesh/mnt/dmfs/b45cfa0a-5037-4389-6ea4-656d04185e57: umount failed: No such file or directory\n">, going into failed state forever
`

Does this have something to do with the fact that we're doing the `zpool export` from inside `require_zfs.sh`?

**Comment by lukemarsden** [comment]
Rebooting the Docker VM fixes this, presumably only until the next time that `dotmesh-server-inner` is terminated...

**Comment by lukemarsden** [comment]
Note discussion [here](https://docs.google.com/document/d/1uuaE5WZux8XAJ5QP67peY7SXoIAaNG2OaDorhd5vjCw/edit#bookmark=id.ioiwu2orgk3s) about how the `zpool export` (which probably triggers this issue) can be moved into a PVPNM only sentinel.

**Comment by alaric-dotmesh** [comment]
I've made `require_zfs.sh` not unmount the pool and all that when in CONTAINER_POOL_MNT mode, which might fix this. Please re-open if it didn't help.

**Comment by lukemarsden** [comment]
confirmed fixed
```
```luke@dot:~$ dm init will-you-live
luke@dot:~$ dm dot show will-you-live
Dot admin/will-you-live:
Master branch ID: f25d04ff-280f-4d7e-45f6-f9c763e08254
Dot is currently selected.
Commits: 0
Dot size: 19.00 kiB (19.00 kiB dirty)
Branches:
* master
   Replication Status:
    server 8d5737c4c51be30c [MASTER] (status: active: waiting, 0 snaps (v113)) is up to date
luke@dot:~$ docker rm -f dotmesh-server-inner
dotmesh-server-inner
luke@dot:~$ dm dot show will-you-live
Dot admin/will-you-live:
Master branch ID: f25d04ff-280f-4d7e-45f6-f9c763e08254
Dot is currently selected.
Commits: 0
Dot size: 19.00 kiB (19.00 kiB dirty)
Branches:
* master
   Replication Status:
    server 8d5737c4c51be30c [MASTER] (status: active: waiting, 0 snaps (v130)) is up to date```
```
