### ISSUE TITLE
support forms of push notification from dotmesh

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#484]
increasingly much stuff is polling dotmesh's API

- dotscience-committer, which does a List every second
- dothub's frontend JS, which polls for dots on your account
- dotscience experiment tracker, polling for provenance graph and run data (involves looking at every commit of every dot)

it would be great to support one or more forms of push notification, so that these things can stop polling

**Comment by Godley** [comment]
I think this is done? We have webhooks now right
