### ISSUE TITLE
More dotscience-affecting memory leaks

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#485]
> it seems to be leaking quite a bit when the following things are polling it:
> - dotscience-committer, which does a List every second
> - dotscience experiment tracker, polling for provenance graph and run data (involves looking at every commit of every dot)

Suggested approach:

Write a script that polls List, and whatever API calls the experiment tracker uses, and see what makes memory usage rise.

When we've narrowed down the operations that cause it, inspect the code to find out why.

**Comment by lukemarsden** [comment]
polling the API seems to cause a memory leak. here are places we poll the API:
- Dotscience committer: https://github.com/dotmesh-io/dotscience-committer/blob/602603aaf584ff04f0ec6cbc07c498c2bd05ba06/hack.py#L96
- JupyterLab plugin backend: https://github.com/dotmesh-io/jupyterlab-plugin/blob/79b1176023f5a97fba4f28dc06645c72ba581b5d/jupyterlab_dotscience_backend/jupyterlab_dotscience_backend/__init__.py#L79
- https://github.com/dotmesh-io/dotscience-ui-spike/blob/master/api/src/logic/leaderboard.js#L111
- Runs: https://github.com/dotmesh-io/dotscience-ui-spike/blob/0f6b9a0ec2b480d372c575cb4b51e73ff5dda0e7/api/src/logic/leaderboard.js#L111
- Provenance graph: https://github.com/dotmesh-io/dotscience-ui-spike/blob/0f6b9a0ec2b480d372c575cb4b51e73ff5dda0e7/api/src/logic/leaderboard.js#L60

**Comment by rusenask** [comment]
This was addressed by lock change to RWMutex where applicable, also some of the locks where inside the loops so they were moved outside. As I understand, performance now is much better, but this can be further improved by optimizing map structures in registry.Registry interface implementation.
