### ISSUE TITLE
list-like RPCs should refer to the registry rather than local fsMachine state

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#489]
i pushed a dot to the dothub yesterday the dothub UI kept flickering between showing it and not showing it

dm list iterates over fsMachines or something crazy rather than inspecting the registry

the API requests were being load balanced between nodes, and some of them didn't have an fsMachine yet presumably

it was a pretty terrible UX

change all the list-like RPCs to query the registry rather than local fsMachine state

**Comment by alaric-dotmesh** [comment]
AllDotsAndBranches (which is what the dothub UI uses, I gather) uses the registry; List uses the mastersCache.

Both do that to get a list of filesystem IDs; both then call getOne to ensure the current user is authorised to see the dot, and bring up the DotmeshVolume struct to return.

Step 1: I'm putting a `GetListOfVolumes` method on InMemoryState, initially based on the code from `List`, and making all three methods use it.

Step 2: I'm going to make `GetListOfVolumes` use the registry.

Step 3: If we still get these flickering states, we fix the registry.

**Comment by alaric-dotmesh** [comment]
Done. Let's see if this fixes our flickering!
