### ISSUE TITLE
dm mount doesn't mount subdots

### ISSUE THREAD

**Issue by danthebaker** [dotmesh-io/dotmesh#491]
Running the `dm mount` command doesn't seem to add mount points for subdots. I would've expected them to appear as sub-folders.

**Comment by alaric-dotmesh** [comment]
Yeah, the `ProcureVolume` method in `api.go` has the default subdot harcoded:

```go
func (dm *DotmeshAPI) ProcureVolume(volumeName string) (string, error) {
	var response string
	namespace, name, err := ParseNamespacedVolume(volumeName)
	if err != nil {
		return "", err
	}
	sendVolumeName := ProcureVolumeName{
		Namespace: namespace,
		Name:      name,
		Subdot:    "__default__",
	}
	err = dm.client.CallRemote(context.Background(), "DotmeshRPC.Procure", sendVolumeName, &response)
	if err != nil {
		return "", err
	}
	return response, nil
}
```

We need to add a subdot param to `ProcureVolume` and make the frontend parse it out of `DOT.SUBDOT` format, with `__default__` as a default; then we can do:

* `dm mount dot /foo` to get the default dot, as usual
* `dm mount dot.subdot /foo` to get a specific subdit
* `dm mount dot.__root__ /foo` to get (as @danthebaker requests) all the subdots as sub-folders!
