### ISSUE TITLE
dm cluster reset breaks extant docker volumes

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#50]
Uninstalling dotmesh with `dm cluster reset` when there are docker volumes which exist which reference dotmesh volumes leaves Docker in a state where it constantly hangs for long periods of time, looking for the `dm` plugin with an exponential backoff.

Make `dm cluster reset` enumerate docker volumes and warn about removing the references before uninstalling dotmesh. It should refuse to do it unless run with `-f`.

**Comment by lukemarsden** [comment]
alternative to https://github.com/dotmesh-io/dotmesh/issues/27

**Comment by lukemarsden** [comment]
related: https://github.com/dotmesh-io/dotmesh/issues/66

**Comment by Godley** [comment]
Users of dotmesh not as high a prio right now, closing.
