### ISSUE TITLE
Abstract the registry

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#500]
As a Dotmesh developer, I'd like to have a more modular codebase with clearly delineated abstractions, so I can replace core components without a lot of painful work.

Therefore, we should make a go interface for the Registry, so we can convert the current implementation into an implementation of that interface. This will allow us to move the registry storage to a better distributed database than etcd in circumstances where one is available, without having to go all over the entire codebase.

**Comment by rusenask** [comment]
Done
