### ISSUE TITLE
Etcd operator startup is sloooow, and upgrades are a pain

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#501]
It takes twenty seconds to create an etcd cluster using the etcd operator; although not the majority of the 5m40s required to build a CI k8s cluster on my laptop by a long stretch, it's a low hanging fruit - and the etcd operator isn't very good at upgrading etcd clusters... It has a tendency to kill the entire cluster and lose all the state.

Therefore, we should consider some alternatives:

- Embed etcd in the dotmesh-server pod, so it doesn't need separate management. Only caveat: We need to make sure to not run more than "7 or so" etcd nodes to keep performance good, so we need some logic for dotmesh-server instances to decide whether to start etcd or not. Possibly including starting etcd up after startup, because another etcd has failed and we're below quota.
- Make the dotmesh operator manage etcd pods.
- Find another off-the-shelf etcd operator.
- Jiust run a deployment or statefulset of etcd, and do some minor work ourselves to configure etcd as a cluster from that.

**Comment by Godley** [comment]
closing as https://github.com/dotmesh-io/ops/issues/107 seems to duplicate this with the solution we've decided on at subsequent team days
