### ISSUE TITLE
remove dependency on docker build for dotmesh-server

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/dotmesh#516]
### User requirement
As a developer, I want the build process to depend only on bazel so that it runs like lightning.

To achieve this we will need to find a way to replicate [these lines](https://github.com/dotmesh-io/dotmesh/blob/master/cmd/dotmesh-server/Dockerfile#L6-L14) in bazel. This probably means we need to use [`new_http_archive`](https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive) for the docker download and [`container_layer`](https://github.com/bazelbuild/rules_docker#container_layer) for the require_zfs one.

### Key acceptance criteria
- [ ] The server container image should be built only with `bazel build //cmd/dotmesh-server:dotmesh-server-img [workspace-and-platform-args-here]`

**Comment by lukemarsden** [comment]
It's also really important that we have the Ubuntu packages here: https://github.com/dotmesh-io/dotmesh/blob/master/cmd/dotmesh-server/Dockerfile#L3

Would we still be using the Dockerfile after this issue is resolved? Which bazel file would these changes be made in? (Asking because I'm curious about maybe picking up this issue.)

**Comment by Godley** [comment]
We wouldn't be using the dockerfile, no.

I've taken a bit of a crack at this on 516-dockerbuild, carry it forward if you like :) The last part is getting the apt-get packages in there, which should go in `/cmd/dotmesh-server/BUILD.bazel` - the [`download_pkgs` rule I've put in there](https://github.com/dotmesh-io/dotmesh/blob/516-dockerbuild/cmd/dotmesh-server/BUILD.bazel#L111) doesn't appear to do much, there's also an install_pkgs rule from the same rule pack which might be it but it's not well documented. ([rule pack loaded here](https://github.com/dotmesh-io/dotmesh/blob/516-dockerbuild/WORKSPACE#L12))

The other changes are in `WORKSPACE` (getting docker and telling bazel how to handle it) and the `container_image` rules in `BUILD.bazel` - appears that `container_layer` has disappeared from the rule pack so I just used images based on top of each other which seems like it's much the same thing 🤷‍♀️
