### ISSUE TITLE
ZFS error in CI: `error-rpc-predict-size`

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#534]
```
Aug 05 07:38:42     		Response event != finished-{push,pull} or peer-up-to-date: <Event maximum-retry-attempts-exceeded: responseEvent: "<Event error-rpc-predict-size: err: \"Response '{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"exit status 1\\\",\\\"data\\\":null},\\\"id\\\":2703387474910584091}\\n' yields error exit status 1\">">
```
see https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/-/jobs/99601

**Comment by lukemarsden** [comment]
Need to improve the capture of stderr from the zfs size prediction command near `error-rpc-predict-size` in the codebase. Make it put the actual stderr from zfs into this error message, re-run the test, figure out if we need to spell something differently in zfs 0.7 case, and if so, add an `if` statement which switches behaviour in the 0.6 vs 0.7 cases.

**Comment by prisamuel** [comment]
Decoupling the CI failures from the bug.

The fundamental issue here is:

PullInitiatorStates does this:

```
