### ISSUE TITLE
dind-flexvolume still has issues with parallel use

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#535]
Seems that on bionic, we can no longer just mount and unmount directly in the flexvolume driver whenever required, as there's trouble with mounting the same device into two locations (sentinal and dotmesh-server).

https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/-/jobs/99595

As the flexvolume driver is asked to mount directly into a container's filesystem (or, at least, into a container-specific path), and we previously relied on Linux letting us mount the same loopback image in more than one location, we probably need to:

1. Have a reference counting system to track multiple mounts of the same PV
2. Mount it just once, in some location alongside the image file
3. bind-mount that out to where it's asked for via the FV API
4. Unmount the bind mounts when asked to via the FV API
5. On the last unmount, unmount the loopback device

And, for extra points, we can also make the dind-flexvolume driver write to .../cleanup-actions.XX file in the test root with explicit unmounts and loopback-device-destroys  to ensure that we always get cleanup of all the mounts it makes.

**Comment by lukemarsden** [comment]
I might have been wrong about this - let's investigate the cause of the error in the linked build:

```
Aug 05 07:42:18 === RUN   TestKubernetesOperator/PVCMakeNew
Aug 05 07:42:19 panic: runtime error: index out of range [recovered]
Aug 05 07:42:19 	panic: runtime error: index out of range
```

**Comment by lukemarsden** [comment]
I might have seen errors in different runs. Kubernetes PVC dind-flexvolume was separately complaining about running out of loopback devices. Investigate more...

**Comment by lukemarsden** [comment]
```
Aug 06 09:39:31 3539: 2018/08/06 09:38:49.476652 [system] result: exit status 32, mount: /dev/loop2 is already mounted or /dotmesh-test-pools/513130633933877-ebb659b0/k8s-cluster-513130633933877-0-node-2/pods/38b78f83-995c-11e8-a1fa-02f42d51d1a0/volumes/dotmesh.io~dind/pvc-38b6dafe-995c-11e8-a1fa-02f42d51d1a0 busy
Aug 06 09:39:31        /dev/loop2 is already mounted on /dotmesh-test-pools/513130633933877-ebb659b0/k8s-cluster-513130633933877-0-node-2/pods/38b8b500-995c-11e8-a1fa-02f42d51d1a0/volumes/dotmesh.io~dind/pvc-38b6dafe-995c-11e8-a1fa-02f42d51d1a0
```
https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/-/jobs/99819

**Comment by lukemarsden** [comment]
Also https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/-/jobs/99818

**Comment by prisamuel** [comment]
Done!
