### ISSUE TITLE
Race condition with updateEtcdAboutSnapshots and subsequent pull from another cluster

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#54]
The TestTwoSingleNodeClusters/Clone test has this case:

```
		d(t, node2, "dm commit -m 'hello'")
[...]
		d(t, node2, "dm commit -m 'again'")
		d(t, node1, "dm pull cluster_1 "+fsname)
```

A nearby change as part of Alaric's deletion work caused this test to fail, as the "success backoff" time in the runWhileFilesystemLives that manages the updateEtcdAboutSnapshots goroutine introduced a 1s sleep between iterations of the loop, which hadn't previously existed.

Result: The first commit triggered the update code, which was then sat in the 1s sleep when the second commit happened, which meant the loop hadn't re-run when the other node attempted to pull; so node2's etcd was lagging behind when node1 contacted it, resulting in confusing error messages:

```
Error applying prelude: [set io.datamesh:meta-timestamp=MTUwNzEzMTYxNjIyMjc0MDEyNw== testpool-1507131563524797308-0-node-0/dmfs/4befd7d9-363b-4929-7653-c4d716842af1@a92c54cf-5a18-4628-5842-36f7974868d8] -> exit status 1: cannot open 'testpool-1507131563524797308-0-node-0/dmfs/4befd7d9-363b-4929-7653-c4d716842af1@a92c54cf-5a18-4628-5842-36f7974868d8': dataset does not exist
```

Removing the sleep made the error go away, but the underlying problem is that a delay in the operation of this asynchronous goroutine can cause such errors.

We can either make the updateEtcdAboutSnapshots loop also update the local cache on the master, rather than waiting for the "echo" via etcd (as referred to in the nearby comments), but that feels a bit hacky.

We could also make the pull code's error retry the entire operation, not just the zfs part, as discussed by Luke:

```
if it’s the case that we’re failing because we’re retrying the thing that won’t work over and over again, and then giving up, we could instead consider moving the start of the retry loop “up” to above calculating what the thing is (i.e. which snapshots to try and pull)

we could also try to fail faster with respect to sending a zfs stream that’s never gonna work. i.e. fail before we start pulling/sending it.

combining the two, we could have quite a nice “retry until the state is ready for us to work with” situation

except that “pull” might end up referring to the wrong thing
```

**Comment by lukemarsden** [comment]
fixed!
