### ISSUE TITLE
deduplicate go client api

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#546]
### User requirement
As a developer of dotmesh, I want to avoid duplication of code so that bug can just get fixed once, and so on.

These are duplicated in:

- dm client
- tests
- dotmesh flexvolume driver (calls Procure)

search for `DotmeshRPC` in the codebase.

### Key acceptance criteria
- [ ] There should only be one instance of https://github.com/dotmesh-io/dotmesh/tree/master/pkg/client

**Comment by rusenask** [comment]
I have started doing this here https://github.com/dotmesh-io/dotmesh-go

**Comment by lukemarsden** [comment]
wait wait i already did it in https://github.com/dotmesh-io/dotmesh/tree/master/pkg/client

**Comment by lukemarsden** [comment]
Let's merge these efforts

**Comment by alaric-dotmesh** [comment]
Mainly done, remainder is now in https://github.com/dotmesh-io/gateway/issues/118
