### ISSUE TITLE
[Question]: navigation through commits and creating branches

### ISSUE THREAD

**Issue by jonathanasquier** [dotmesh-io/dotmesh#549]
Hi,
I understand it is possible to reset a branch to a commit hash, or checking out branches previously created.
But is it possible to create branches on commit hashes created earlier on the current branch and checking them out?

Thanks!

**Comment by lukemarsden** [comment]
Please clarify your question? Thanks!

**Comment by jonathanasquier** [comment]
Nice!
Erm I started trying dotmesh out exactly 55 mins ago, so I'm probably going to finish the tutorials before starting hacking everything ^^

**Comment by alaric-dotmesh** [comment]
I'd be glad to assist if you fancy giving it a try :-)

In the meantime, I'm going to close the issue as the question is answered!
