### ISSUE TITLE
I broke my dotmesh installation

### ISSUE THREAD

**Issue by jonathanasquier** [dotmesh-io/dotmesh#551]
I reseted re inited the cluster, removed the .dotmesh folder but dotmesh won't start anymore
the dotmesh-server-inner stacks this way:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                   │
│   [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc072e8]                                                                                    │
│   goroutine 94 [running]:                                                                                                                                   │
│   main.s3PushInitiatorState(0xc42001e900, 0xecf550)                                                                                                         │
│    cmd/dotmesh-server/s3pushinitiatorstate.go:31 +0x3a8                                                                                                     │
│   main.(*fsMachine).run.func1(0xc42001e900)                                                                                                                 │
│    cmd/dotmesh-server/statemachines.go:124 +0x3b                                                                                                            │
│   created by main.(*fsMachine).run                                                                                                                          │
│    cmd/dotmesh-server/statemachines.go:122 +0x2ac
```
```
time="2018-08-16T14:55:19Z" level=info msg="findRelatedContainers setting /dotmesh.io/filesystems/containers/705e3e8c-17fc-414e-471e-c55e26eb7a28 to {\   │
│   "Server\":\"f7613db074846280\",\"Containers\":[]}"                                                                                                        │
│   panic: runtime error: index out of range                                                                                                                  │
│   goroutine 313 [running]:                                                                                                                                  │
│   main.s3PushInitiatorState(0xc420389680, 0xecf550)                                                                                                         │
│    cmd/dotmesh-server/s3pushinitiatorstate.go:40 +0x1a46                                                                                                    │
│   main.(*fsMachine).run.func1(0xc420389680)                                                                                                                 │
│    cmd/dotmesh-server/statemachines.go:124 +0x3b                                                                                                            │
│   created by main.(*fsMachine).run                                                                                                                          │
│    cmd/dotmesh-server/statemachines.go:122 +0x2ac
```
most of dm commands break like this: 
```
➜ dm list
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

Unable to connect to any of the addresses attempted: [{Scheme:http Hostname:127.0.0.1 Port:32607} {Scheme:http Hostname:127.0.0.1 Port:6969}], errs: [Post http://127.0.0.1:32607/rpc: dial tcp 127.0.0.1:32607: connect: connection refused Post http://127.0.0.1:6969/rpc: dial tcp 127.0.0.1:6969: connect: connection refused]

```

This started when I started messing around with S3 and tried to push to a remote. Since then I couldn't manage to unbreak my cluster :'(

**Comment by lukemarsden** [comment]
Thanks for the bug report @jonathanasquier! I've asked my colleague @Godley to take a look at this :+1:

**Comment by Godley** [comment]
Agh, looks like we have a array-index-out-of-range problem there, sorry about that. Did you commit before attempting a push @jonathanasquier ?

**Comment by jonathanasquier** [comment]
I tried a lot of stuff that might have been:
- pushing with wrong arguments
- pushing with a wrong s3 policy
- pushing on unexisting buckets
- pushing an empty/not commited dot

**Comment by Godley** [comment]
Nice selection of test cases there :) I think it was the final one that did this so what I just pushed should fix that now. If you could run:

`sudo curl -sSL -o /usr/local/bin/dm https://get.dotmesh.io/unstable/master/$(uname -s)/dm && dm cluster upgrade`
And try doing that again it should work correctly this time. In the meantime I'll check whether we have testcases covering this...

**Comment by Godley** [comment]
Thanks for trying to break it! :D I think it's the last one that's caused this problem - should be fixed now, just waiting for CI to release it. I'll look into whether we have a testcase covering that already...

**Comment by Godley** [comment]
Right that should be in the wild now. @jonathanasquier If you could run:
`sudo curl -sSL -o /usr/local/bin/dm https://get.dotmesh.io/unstable/master/$(uname -s)/dm && dm cluster upgrade` which will mean your cluster's running latest master then that should fix it, let me know if it doesn't.

**Comment by jonathanasquier** [comment]
It works! Awesome thank you!
How come this single command prevented the whole cluster to start properly even after a reset?

**Comment by lukemarsden** [comment]
If you're interested in knowing how to _completely_ wipe your system, there's a local docker volume with the etcd state, and `/var/lib/dotmesh` on your docker VM or docker host where the data files reside. If you do a `dm cluster reset`, destroy both and start up again, everything should be _really_ reset.
