### ISSUE TITLE
auto-commits from s3 api show up as "undefined" user in ui

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/dotmesh#557]
### User requirement
As a dothub user, I want to know who or what wrote my commits so that I understand why they're there.

This may be a UI problem but we could also fix it on the backend - commits after a "put" operation on the s3 api have no author, and thus show up as undefined in the ui:
![screen shot 2018-08-20 at 10 49 37](https://user-images.githubusercontent.com/4128117/44333468-c85da580-a466-11e8-9788-0a4741bccc2f.png)

Who should be the user? the person who uploaded via the api or the system? Suspect this may also be an issue when pulling from an s3 remote.

**Comment by lukemarsden** [comment]
In the browser upload case, I think it should be the authenticated user. In the s3 remote case, it's probably the system.

**Comment by Godley** [comment]
Closing this for now as it's covered on the S3 api portion. May reopen or start a new one if there's problems in the S3 remote
