### ISSUE TITLE
[2d] file uploads going over etcd might be causing empty string etcd values

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#579]
Let's just proxy the HTTP requests to the S3 API to the right node for the dot in question, and stream the PUT/GET directly to the filesystem. We should never buffer the files in memory, let alone in etcd.

ACs:

- [x] It should be possible to upload arbitrarily large files (in particular, >2MiB files are a good test case to validate that we've avoided etcd limits).
- [x] In particular, it should be possible to upload files larger than the server memory.
- [x] The system should continue to work afterwards (eg, we don't break something).

**Comment by alaric-dotmesh** [comment]
ACs:

- [ ] It should be possible to upload arbitrarily large files (in particular, >2MiB files are a good test case to validate that we've avoided etcd limits).
- [ ] In particular, it should be possible to upload files larger than the server memory.
- [ ] The system should continue to work afterwards (eg, we don't break something).
