### ISSUE TITLE
Allow deletion of branches

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#58]
As per the comment in rpc.go:DeleteVolume, it should easily be possible to limit it to only delete specified branches (with the caveat that ZFS restricts us to only deleting snapshots with no children, so deleting a branch will kill all the branches it's parent to, unless we promote them out).

**Comment by Godley** [comment]
OLDDDDD. Reopen if still relevant/needed/has prio etc
