### ISSUE TITLE
[0.5d] Change S3 API commit message to be less confusing

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/dotmesh#580]
Most of our users for the S3 api come from dotscience, to them it seems confusing that the commit message contains the word "s3" and may suggest some connection with AWS.

We should change this so that maybe the metadata indicates the type of commit was automated and from a file coming through the S3 compatible api, but that the commit message maybe just says "file x uploaded"

**Comment by alaric-dotmesh** [comment]
Done.
