### ISSUE TITLE
Review use of etcd as a message queue

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#581]
### User requirement
As a Dotmesh user, I don't want etcd being used as a message queue inside Dotmesh, so that I can have fewer problems with it getting overloaded.

### Key acceptance criteria
- [ ] Everything that works now should continue to work, just as well.
- [ ] Dotmesh should still still work when a node is down and comes back - queued activities that were waiting for the node to return should seamlessly resume when the node comes back, within a reasonable timeframe.
- [ ] It should continue to work when there is a lot of activity in the system (defined as lots of operations that cause requests to be sent to state machines); throughput should reach a reasonable peak as the applied load increases and not drop much as applied load continues to rise beyond that point.
- [ ] It should not require any additional steps for the user during installation (eg, any third-party message queue tools we decide to use should be installed seamlessly by `dm cluster init` or the Dotmesh Operator)

### See Also

 - #579: File uploads using statemachine requests particularly exacerbate the weaknesses of the current etcd message queue; whether this issue provides a good enough message queue that we can send bulk file uploads through it or if a different mechanism is still needed is an open question (but note that file uploads may be much larger than RAM in future).

**Comment by Godley** [comment]
I think this is duplicated/superceded by #602
