### ISSUE TITLE
Consider alternatives to etcd for system state

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#582]
#581 considers not using etcd as a message queue; this issue is about reviewing our remaining uses of it.

An etcd dump of a running system on my laptop shows this structure in etcd, requests/responses aside:

```
"/dotmesh.io/registry/filesystems/NAMESPACE/NAME",
"/dotmesh.io/servers/addresses/SERVER",
"/dotmesh.io/servers/states/SERVER/FSID",
"/dotmesh.io/servers/snapshots/SERVER/FSID",
"/dotmesh.io/users/UID",
"/dotmesh.io/dotmesh.io ",
"/dotmesh.io/dotmesh.io /nameidx",
"/dotmesh.io/dotmesh.io /nameidx/admin",
"/dotmesh.io/filesystems/live/FSID",
"/dotmesh.io/filesystems/masters/FSID",
"/dotmesh.io/filesystems/transfers/TRANSFERID",
"/dotmesh.io/filesystems/dirty/FSID",
"/dotmesh.io/filesystems/containers/FSID",
```

(No, I don't know what the `dotmesh.io /nameidx` thing is about, is it a bug?)

Perhaps much of it would be better stored in a "proper database" (eg, psql), although there are some critical atomic updates performed in the `filesystems/masters` section to ensure clean handover; I hear a rumour (somebody said that @lukemarsden said) that we could ask Kubernetes to track that for us, but I'm not sure what we'd then do for non-k8s deployments.

Have a think, form a plan!

**Comment by Godley** [comment]
related - #602

**Comment by alaric-dotmesh** [comment]
We now use nats for messaging, have the option to run BoltDB in single-node cases, and have upgraded to use the latest etcd client when we DO use etcd, so hopefully our etcd woes are a thing of the past!
