### ISSUE TITLE
If we continue to use etcd, consider better ways to deploy it

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#583]
Issues #581 and #582 call our use of etcd into question, if it's still in use in some form, we should reconsider the value of the etcd operator.

It's:

- Complicated internally, which is a bad sign.
- Prone to mysterious behaviour, like when the production cluster lots all its etcd nodes (somehow) and the operator wouldn't start new ones until we deleted and re-created the `EtcdCluster` object. All our etcd data got lost in the process.
- Really slow to start (it's a big delay in k8s test cluster setup) for some reason.

So perhaps we can just embed etcd in the dotmesh server, or start a cluster up from the dotmesh operator, or something else. Assuming we still use etcd at all.

**Comment by Godley** [comment]
We have a lot of issues that talk about this, e.g not using it, installing it without the operator...going to close this as duplicate
