### ISSUE TITLE
[0.5d] pull out `dm` client interactions into the `client` pkg

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/dotmesh#591]
### User requirement
As a developer, I would like to use dotmesh from my go program without having to shell out to a binary or dig into the source code to find the right import path.

Specifically we could probably just move `cmd/dm/pkg/remotes` code to be in `pkg/client`, change the imports elsewhere and be done with it :) This would also get us closer to following the [standard go project layout](https://github.com/golang-standards/project-layout) (by one package)

**Comment by alaric-dotmesh** [comment]
Done. I did both `api.go` and `remotes.go`, meaning that users of the client library can now access remotes set up in `~/.dotmesh/config`, which could be pretty handy for CLI tools like `ds`!
