### ISSUE TITLE
registry reset functionality

### ISSUE THREAD

**Issue by rusenask** [dotmesh-io/dotmesh#619]
currently there's a:
```

		// From time to time, the entire registry will be deleted (see rpc.go
		// RestoreEtcd). Detect this case and wipe out the registry records as
		// commonly dots will be re-owned in this scenario.

		if node.Node.Key == fmt.Sprintf("%s/registry", ETCD_PREFIX) {
			s.resetRegistry()
			return fmt.Errorf(
				"intentionally reloading from etcd because " +
					"we noticed the registry disappear.",
			)
		}

```
 in the etcd watcher. That RPC should have a better way of telling the remaining cluster nodes to reset their registries. If this is still in use, let's change it to a NATS message, if not, don't reimplement it.

**Comment by lukemarsden** [comment]
this is how `dm cluster etcd-restore` works, so yea, still in use...

**Comment by rusenask** [comment]
this is done, reset is performed via nats message
