### ISSUE TITLE
[EXTRA] tar endpoint from a directory in a snapshot

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#639]
### User requirement
As a dotmesh API consumer, I want to download a tarball of a directory in a snapshot of a datadot so that I can download many files in a single API call.

### Key acceptance criteria
- [x] It should stream a tarball back from a certain path in a snapshot of a dot with fixed memory usage

**Comment by rusenask** [comment]
how big can these files be?

**Comment by lukemarsden** [comment]
arbitrarily large

streaming the output of `tar cf` back to the user would be one way to do it memory efficiently

**Comment by rusenask** [comment]
The same strategy can be used as we have for individual files, writing directly to the client connection. Just the actual archive creation should be done in a temp dir and not memory

**Comment by lukemarsden** [comment]
why double the amount of disk space used and add cleanup complexity when we can just stream the output of `tar cf` back to the user?

**Comment by rusenask** [comment]
yeah, good point, tar writer can do that

**Comment by alaric-dotmesh** [comment]
https://godoc.org/archive/tar looks nice and easy to use, rather than shelling out to `tar`.
