### ISSUE TITLE
dm pull acts confusingly

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#67]
I had intended to write `dm clone`, but wrote `dm pull`, which then said this:

```
luke@beast:~/moby-counter$ dm pull origin luke4/moby_counter_demo
Pulling luke4/moby_counter_demo from origin:luke5/moby_counter_demo
Response '{"jsonrpc":"2.0","error":{"code":-32000,"message":"Both local and remote filesystems don't exist. \u0026{Peer:cloud.datamesh.io User:luke5 ApiKey:XXX Direction:pull LocalNamespace:luke4 LocalFilesystemName:moby_counter_demo LocalCloneName: RemoteNamespace:luke5 RemoteFilesystemName:moby_counter_demo RemoteCloneName: TargetSnapshot:}","data":null},"id":5577006791947779410}
' yields error Both local and remote filesystems don't exist. &{Peer:cloud.datamesh.io User:luke5 ApiKey:XXX Direction:pull LocalNamespace:luke4 LocalFilesystemName:moby_counter_demo LocalCloneName: RemoteNamespace:luke5 RemoteFilesystemName:moby_counter_demo RemoteCloneName: TargetSnapshot:}
```
Also the error shouldn't show the password in plain text!

**Comment by lukemarsden** [comment]
issues:
1. the model is slightly complicated (you can have namespaces locally)
2. behaviour for clone, pull, push tries to make it make sense - it's complicated
3. have we implemented and documented the complicated rules correctly?

possible solutions:
1. stop having namespaces locally?
2. distinguish between admin-on-hub and admin-as-local-user? disallow local namespaces in the latter case?

**Comment by Godley** [comment]
Closing as old and low prio, reopen when needed
