### ISSUE TITLE
[0.5d] pushPeerState should set status to include bytes transferred

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#720]
currently it shows as `running, 1 commits`, but ideally it should include MB/sec and MB transferred

`pkg/fsm/fsm_push_peer.go` probably gets this in `case <-receiveProgress` but throws it away, could set status in `f.transitionedTo("pushPeerState", "<insert status here>")` instead

**Comment by lukemarsden** [comment]
important because polish is important

**Comment by lukemarsden** [comment]
needs a UI change in the frontend when workspace-status is rendered.

**Comment by alaric-dotmesh** [comment]
Please describe the UI change in the frontend that you'd like!

**Comment by lukemarsden** [comment]
Relates to https://github.com/dotmesh-io/frontend-ng/issues/625

In addition to the fixes in that issue, should show the new info available thanks to this issue in that same grey bar

So like "Synchronizing data with runner, 213.2/342.3MB at 12.2MB/sec..."

**Comment by alaric-dotmesh** [comment]
Ok, as far as I can tell, the UI is based on the status info in the DotmeshRPC.Get call, which looks like this during a push:

```
{
  "Branch": "",
  "CommitCount": 1,
  "DirtyBytes": 0,
  "ForkParentId": "",
  "ForkParentSnapshotId": "",
  "Id": "fc1155b6-9b29-4dee-80b1-1e6e5c85b263",
  "Master": "7bd2e339648fedb0",
  "Name": {
    "Name": "pushtest",
    "Namespace": "admin"
  },
  "ServerStates": {
    "7bd2e339648fedb0": "pushPeerState"
  },
  "ServerStatuses": {
    "7bd2e339648fedb0": "running, 1 commits"
  },
  "SizeBytes": 1471407104
}
```

...the actual state message isn't included, so I'll need to include that to enable https://github.com/dotmesh-io/frontend-ng/issues/625 to use this info I'm adding!

**Comment by alaric-dotmesh** [comment]
Done in dotmesh version 8922c68918b320fa9e8562788dccfb91e7fbd1cc
