### ISSUE TITLE
Update workspace status state once push has finished

### ISSUE THREAD

**Issue by danthebaker** [dotmesh-io/dotmesh#744]
The workspace status doesn't update from `pushPeerState` once the push is complete, causing the frontend to show an incorrect status message. See screenshot below. No runner is connected but the frontend shows that the runner is pushing back to the hub.

<img width="1592" alt="Screenshot 2019-08-22 at 13 27 05" src="https://user-images.githubusercontent.com/1846998/63514605-dbbfa880-c4e0-11e9-8035-ea57eb05f914.png">

**Comment by lukemarsden** [comment]
Bumped to high/high as our Dotscience SaaS users seem to be getting confused by this.
