### ISSUE TITLE
Usability: Complain if you try to push a branch (or master) with zero commits on

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/dotmesh#77]
d(t, aliceNode.Container, "dm checkout -b mustard")
		d(t, aliceNode.Container, dockerRun("cress")+" touch /foo/mustard")
		d(t, aliceNode.Container, "dm push cluster_0 cress mustard --remote-volume alice/cress")

...make a branch, do something on it, push WITHOUT COMMITTING. Should moan that there's no commits to push, so user isn't surprised when `/foo/mustard` doesn't appear elsewhere after pulling.

**Comment by lukemarsden** [comment]
let's do https://github.com/dotmesh-io/dotmesh/issues/159 instead
