### ISSUE TITLE
Frequent errors when first starting Jupyter

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#788]
https://dotscience.slack.com/archives/C7PHSRL82/p1578674668057000

@lukemarsden reports:

> I get this error fairly often when starting jupyter on a runner (when the runner didn’t yet have the project dot). always resolves when running again but it’s a bad look. is there some asynchrony in dotmesh knowing its commits after an initial pull/clone?

![image](https://user-images.githubusercontent.com/31884165/72172697-b66b0280-33cd-11ea-8c7b-63cf92248214.png)

> in this case it’s the machine under my desk in Bristol, which is quite fast bare-metal machine in case that makes a difference

**Comment by itamarst** [comment]
Digging through the code, I eventually found `InitFilesystemMachine` in dotmesh, which does the following:

```go
		go s.filesystems[filesystemId].Run() // concurrently run state machine

		return s.filesystems[filesystemId], false
```

This suggests filesystem creation happens in background, if I'm interpreting code correctly...
