### ISSUE TITLE
branch size info oscillates wildly

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#90]
<img width="542" alt="screen shot 2017-10-27 at 09 29 00" src="https://user-images.githubusercontent.com/264658/32094937-5c0a5fec-baf9-11e7-9959-5b68d8a5fdd7.png">

<img width="545" alt="screen shot 2017-10-27 at 09 29 06" src="https://user-images.githubusercontent.com/264658/32094942-5eacb556-baf9-11e7-86a9-4c67e2a7525f.png">

**Comment by alaric-datamesh** [comment]
See also https://github.com/dotmesh-io/frontend/issues/11 - possibly related

**Comment by alaric-dotmesh** [comment]
This is believed to be done
