### ISSUE TITLE
Unable to create a new branch until at least one commit on master

### ISSUE THREAD

**Issue by deitch** [dotmesh-io/dotmesh#98]
If you try to create a new branch before doing a commit on master, it fails with an error (confusing unless you already get how it works).

1. Try the demo (or any other way of spinning up a volume)
2. Look at the status, looks like `BRANCH=master`

```
$ dm list
Current remote: local (use 'dm remote -v' to list and 'dm remote switch' to switch)

  VOLUME        BRANCH  SERVER            CONTAINERS            SIZE       COMMITS  DIRTY
* moby_counter  master  a96323d6807a7a44  /mobycounter_redis_1  19.00 kiB  0        19.00 kiB
```

3. Try to get a new branch:

```
$ dm checkout -b one-logo
No commits match HEAD
```

Shouldn't the starting point of a branch be a commit? If I `git init` somewhere, I can go into `git branch` right away.

**Comment by lukemarsden** [comment]
This will be solved by https://github.com/dotmesh-io/dotmesh/issues/159
